<?php
/** @var OmnyfyCustomzation\ConfigurableProduct\Pricing\Render\FinalPriceBox $block */
$regularPriceModel = $block->getPriceType('regular_price');

?>
    <span class="normal-price"><?= $block->getConfigurableFinalPrice() ?></span>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <span class="old-price sly-old-price no-display">
        <?= /* @noEscape */
        $block->renderAmount($regularPriceModel->getAmount(), [
            'display_label' => __('Regular Price'),
            'price_id' => $block->getPriceId('old-price-'),
            'price_type' => 'oldPrice',
            'include_container' => true,
            'skip_adjustments' => true
        ]); ?>
    </span>
<?php endif; ?>