<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<?php
$helper = $this->helper('Omnyfy\VendorReview\Helper\Data');
$vendorHelper = $this->helper('Omnyfy\VendorReview\Helper\Vendor');
?>
<?php if($block->getCollectionSize()): ?>
<div id="product-review-container" data-role="product-review"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
<?php endif; ?>
<?php if(!$helper->isDisplayProductReviewOnOrder() || !$vendorHelper->isVendorReviewEnabled()): ?>
<?= $block->getChildHtml() ?>
<?php endif; ?>

