<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */
$_item = $block->getItem();
$block->setPriceDataObject($_item);

/** @var OmnyfyCustomzation\Mcm\Helper\Data $helper */
$helper = $this->helper(\OmnyfyCustomzation\Mcm\Helper\Data::class);
$product = $helper->getProductById($_item->getProductId());
?>


<td class="col-thumbnail">
    <img src="<?= $helper->getThumbnailItem($product) ?>" alt="<?= $product->getName() ?>" width="100">
</td>
<td class="col-product"><?php echo $block->getColumnHtml($_item, 'name') ?></td>
<td class="col-price">
    <?php echo $block->getColumnHtml($_item, 'price'); ?>
</td>
<td class="col-qty"><?php echo $block->getColumnHtml($_item, 'qty') ?></td>
<td class="col-qty-invoice">
    <?php if ($block->canEditQty()) : ?>
        <input type="text" class="input-text admin__control-text qty-input"
               name="invoice[items][<?php /* @escapeNotVerified */
               echo $_item->getOrderItemId() ?>]"
               value="<?php /* @escapeNotVerified */
               echo $_item->getQty() * 1 ?>"/>
    <?php else : ?>
        <?php /* @escapeNotVerified */
        echo $_item->getQty() * 1 ?>
    <?php endif; ?>
</td>
<td class="col-subtotal">
    <?php echo $block->getColumnHtml($_item, 'subtotal'); ?>
</td>
<td class="col-tax"><?php /* @escapeNotVerified */
    echo $block->displayPriceAttribute('tax_amount') ?></td>
<!--    <td><?php echo $block->getColumnHtml($_item, 'sellerfees'); ?></td>
    <td><?php echo $block->getColumnHtml($_item, 'categoryfees'); ?></td>
    <td><?php echo $block->getColumnHtml($_item, 'taxpercentageonfees') ?></td>-->
<td class="col-discount"><?php /* @escapeNotVerified */
    echo $block->displayPriceAttribute('discount_amount') ?></td>
<td class="col-total last">
    <?php echo $block->getColumnHtml($_item, 'total'); ?>
</td>
