<?php
/**
 * Cms article list item template
 *
 * @var $block \OmnyfyCustomzation\CmsBlog\Block\Blog\BlogList
 */

$blogs = $block->getBlogCollection();
$popularTags = $block->getPopularTag();
$categories = $block->getCategories();
$currentCategory = $block->getCurrentCategoryParam();
$currentTag = $block->getCurrentTagParam();
?>
<div class="blog-categories">
    <a href="<?= $block->escapeHtml($block->getPageUrl()) ?>"
       class="blog-category <?= !$currentCategory ? 'active' : '' ?>">
        <?= __('All') ?>
    </a>
    <?php foreach ($categories as $category): ?>
        <a href="<?= $block->escapeHtml($block->getCategoryUrl($category)) ?>"
           class="blog-category <?= $category->getIdentifier() == $currentCategory ? 'active' : '' ?>">
            <?= $category->getTitle() ?>
        </a>
    <?php endforeach; ?>
</div>
<div class="blogs-container">
    <p class="popular-tags"> <?= _('Popular #Tag') ?>
        <?php foreach ($popularTags as $tag) : ?>
            <?php if ($tag['identifier']): ?>
                <span class="blog-tag <?= $tag['identifier'] == $currentTag ? 'active' : '' ?>">
                    <a href="<?= $block->escapeHtml($block->getTagUrl($tag['identifier'])) ?>"
                       class="popular-tag">
                        #<?= $tag['title'] ?>
                    </a>
                    <?php if ($tag['identifier'] == $currentTag): ?>
                        <a class="clear-tag" href="<?= $block->escapeHtml($block->clearTag()) ?>"><i class="fal fa-times"></i></a>
                    <?php endif; ?>
                </span>
            <?php endif; ?>
        <?php endforeach; ?>
    </p>
    <div class="blogs">
        <?php foreach ($blogs as $blog) : ?>
            <div class="blog-container">
                <div class="blog">
                    <div class="blog-image"
                         style="background-image: url(<?= $block->escapeHtml($block->getBlogImage($blog)); ?>)">
                    </div>
                    <div class="blog-info">
                        <p class="blog-title">
                            <a class="blog-url" href="<?= $blog->getArticleUrl() ?>"><?= $blog->getTitle() ?></a>
                        </p>
                        <p class="blog-description"><?= $blog->getShortDescription() ?></p>
                        <p class="blog-tags">
                            <?php foreach ($blog->getRelatedTags() as $tag): ?>
                                <a href="<?= $block->escapeHtml($block->getTagUrl($tag->getIdentifier())) ?>">#<?= $tag->getTitle() ?></a>
                            <?php endforeach; ?>
                        </p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
