<?php
$rebateData = $block->getData('rebate_data');
$invoiceTo = $block->getData('invoice_to');
$invoiceFrom = $block->getData('invoice_from');
$invoiceItems = $block->getData('invoice_items');
$totalRebate = $block->getData('total_rebate');
$paymentDetail = $block->getData('payment_detail');
$helperRebateUI = $this->helper('Omnyfy\RebateUI\Helper\Data');
$logoSrc = $block->getData('logo_url');
?>
<body class="rebate">
    <!--HEADING-->
    <table style="table-layout: fixed; width: 100%; line-height: 10px; font-family: Arial, Helvetica, sans-serif; font-weight: bold">
        <tr>
            <td style="width:80%; font-size: 28px; text-align: left; padding-top: 25px">
                <?= $rebateData['mo_name']; ?>
            </td>
            <td>
                <img src="<?= $logoSrc; ?>" style="display: block; max-height: 60px; max-width: 132px; width: 100%; text-align: right;">
            </td>
        </tr>
    </table>
    <div style="margin-top: 30px;"></div>

    <div style="font-size: 32px; margin-bottom: 30px; font-family: Arial, Helvetica, sans-serif; font-weight: bold; padding-left: 5px;">
        <b><?= $rebateData['title']; ?></b>
    </div>

    <table class="header" cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; font-family: Arial, Helvetica, sans-serif; font-size: 13px;">
        <tr>
            <td style="text-align: left;">
                <b><?= __('Invoice To') ?></b>
            </td>
            <td style="text-align: right;">
                <b><?= __('Invoice from') ?></b>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;"><?= $invoiceTo['name'] ?></td>
            <td style="text-align: right;"><?= $invoiceFrom['invoice_name'] ?></td>
        </tr>
        <tr>
            <td style="text-align: left;"><?= $invoiceTo['address'] ?></td>
            <td style="text-align: right;"><?= __('Tax Number: ') . $invoiceFrom['tax_number'] ?></td>
        </tr>
        <tr>
            <td></td>
        </tr>
        <tr>
            <td style="text-align: left;">
                <b><?= $rebateData['title_invoice']; ?></b>
            </td>
            <td style="text-align: right;">
                <?= $invoiceFrom['address_line1'] . ', ' . $invoiceFrom['address_line2'] ?>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;"><?= __('Rebate Tax Invoice #: %1', $rebateData['invoice_tax']) ?></td>
            <td style="text-align: right;">
                <?= $invoiceFrom['city'] . ', ' . $invoiceFrom['post_code'] . ', ' . $invoiceFrom['region_name'] ?>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;"><?= __('Invoice Date: %1', $rebateData['invoice_date']) ?></td>
            <td style="text-align: right;"><?= $invoiceFrom['country_name'] ?></td>
        </tr>
        <tr>
            <td style="text-align: left;"><?= __('Invoice Due Date: %1', $rebateData['invoice_due']) ?></td>
        </tr>
        <?php if ($rebateData['invoice_period']): ?>
            <tr>
                <td style="text-align: left;"><?= __('Invoice Period: %1', $rebateData['invoice_period']) ?></td>
            </tr>
        <?php endif; ?>
    </table>

    <!--REBATE NAME-->
    <div style="margin-top: 30px;"></div>
    <table class="rebate-name" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 1.3; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif;">
        <tr style="background-color: #F6F6F8;">
            <td style="width: 50%; text-align: left; padding: 10px;">
                <b><?= __('Rebate Name') ?></b>
            </td>
            <td style="width: 25%; text-align: right; padding: 10px;">
                <b><?= __('Amount (Incl Tax)') ?></b>
            </td>
            <td style="width: 25%; text-align: right; padding: 10px;">
                <b><?= __('Tax include') ?></b>
            </td>
        </tr>
        <?php foreach ($invoiceItems as $invoiceItem): ?>
            <tr>
                <td style="width: 50%; text-align: left; padding-top: 15px; padding-left: 10px;"><?= $invoiceItem['rebate_name'] ?></td>
                <td style="width: 25%; text-align: right; padding-top: 15px; padding-left: 10px;"><?= $helperRebateUI->formatToBaseCurrency($invoiceItem['rebate_total_amount']) ?></td>
                <td style="width: 25%; text-align: right; padding-top: 15px; padding-left: 10px;"><?= $helperRebateUI->formatToBaseCurrency($invoiceItem['rebate_tax_amount']) ?></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="3" style="padding-left: 10px; padding-right: 10px;">
                <hr style="border-bottom: solid 2px #ebebef;">
            </td>
        </tr>
        <tr>
            <td style="width: 50%; text-align: center;"><?= __('Total Rebate Payable') ?></td>
            <td style="width: 25%; text-align: right;"><?= $helperRebateUI->formatToBaseCurrency($totalRebate['total_amount']) ?></td>
            <td style="width: 25%; text-align: right;"><?= $helperRebateUI->formatToBaseCurrency($totalRebate['total_tax']) ?></td>
        </tr>
    </table>

    <!--PAYMENT DETAIL-->
    <div style="margin-top: 30px;"></div>
    <table class="payment-detail" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif; background-color: #F6F6F8;">
        <tr>
            <td style="text-align: left; padding-left: 10px; padding-top: 15px;">
                <b><?= __('Payment Details') ?></b>
            </td>
        </tr>
        <tr>
            <td colspan="3" style="padding-left: 10px; padding-right: 10px;">
                <hr style="border-bottom: solid 2px #ebebef;">
            </td>
        </tr>
        <?php if(!empty($paymentDetail)): ?>
        <?php foreach ($paymentDetail as $detail): ?>
            <tr>
                <td style="text-align: left; padding-left: 10px;"><?= $detail ?></td>
            </tr>
        <?php endforeach; ?>
        <?php endif ?>
    </table>
</body>
