<?php /** @var \OmnyfyCustomzation\Navigation\Block\Navigation\State $block */ ?>
<?php
$filters = $block->getActiveFilters();
$value = [];
$filterList = [];
$labelList = [];
?>
<?php if (!empty($filters)): ?>
    <div id="am-shopby-container" class="amshopby-filter-current filter-current" data-am-js="shopby-container"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false }}'>
        <span class="block-subtitle filter-current-subtitle"
              role="heading"
              aria-level="2"
              data-role="title"
              data-count="<?= /* @noEscape */
              count($filters); ?>">
            <?= $block->escapeHtml(__('Now Shopping by')) ?>
        </span>
        <ol class="amshopby-items items">
            <?php foreach ($filters as $filter): ?>
                <?php
                /** @var \Magento\Catalog\Model\Layer\Filter\Item $filter */
                $filterSetting = $block->getFilterSetting($filter->getFilter());
                $value = $value ?: $filter->getValue();
                $resultValue = $block->getFilterValue($value, $filter);
                $currentFilterName = __('Remove') . " " . $block->stripTags($block->getFilterLabel($filter));
                ?>
                <?php if (!in_array($filter->getLabel(), $filterList)): ?>
                    <?php
                    $filterList[] = $filter->getLabel();
                    $filterLabel = $block->getFilterLabel($filter);
                    ?>
                    <li class="item amshopby-item" data-am-js="shopby-item"
                        data-container="<?= $filter->getFilter()->getRequestVar() ?>"
                        data-value="<?= $block->getDataValue($resultValue) ?>">
                        <a class="amshopby-remove"
                           href="<?= $block->escapeUrl($block->getClearLinkUrl($filter, $filterLabel, $labelList)) ?>"
                           title="<?= $block->escapeHtml($currentFilterName); ?>">
                        </a>
                        <span class="amshopby-filter-name">
                        <?= $block->escapeHtml(__($filterLabel)); ?>
                    </span>
                        <div class="amshopby-filter-value">
                            <?= $block->viewLabel($filter); ?>
                        </div>
                    </li>
                    <?php $labelList[] = $filterLabel ?>
                <?php endif; ?>

            <?php endforeach; ?>
            <li class="amshopby-button">
                <?php if ($block->getUnfoldedCount() && $block->getUnfoldedCount() < count($filters)): ?>
                    <?= /* @noEscape */
                    $block->createShowMoreButtonBlock() ?>
                <?php endif; ?>
            </li>
        </ol>

        <script type="text/x-magento-init">
            {
                "[data-am-js='shopby-container']": {
                    "amShopbyFilterContainer": {
                            "collectFilters": <?= $block->collectFilters(); ?>,
                            "numberOfUnfoldedOptions": <?= $block->escapeHtml($block->getUnfoldedCount()) ?>
                       }
                }
            }



        </script>
    </div>
<?php endif; ?>
