<?php
$orderData = $block->getData('order_data');
$invoiceData = $block->getData('invoice_data');
$soldData = $block->getData('sold_data');
$shippingData = $block->getData('shipping_data');
$orderItems = $block->getData('order_items');
$vendorInfo = $block->getData('vendor_info');
$totals = $block->getData('totals');
$mcmHelper = $this->helper('Omnyfy\Mcm\Helper\Data');
$logoSrc = $block->getData('logo_url');
?>
<body class="credit_memo">
    <!--HEADING-->
    <table style="table-layout: fixed; width: 100%; line-height: 10px; font-family: Arial, Helvetica, sans-serif; font-weight: bold">
        <tr>
            <td style="width:80%; font-size: 28px; text-align: left; padding-top: 25px">
                <?= $orderData['mo_name']; ?>
            </td>
            <td>
                <img src="<?= $logoSrc; ?>" style="display: block; max-height: 60px; max-width: 132px; width: 100%; text-align: right;">
            </td>
        </tr>
    </table>
    <div style="margin-top: 30px;"></div>

    <div style="font-size: 32px; margin-bottom: 30px; font-family: Arial, Helvetica, sans-serif; font-weight: bold; padding-left: 5px;">
        <b><?= __('Credit Memo') ?></b>
    </div>

    <table class="header" cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; font-family: Arial, Helvetica, sans-serif; font-size: 13px;">
        <tr>
            <td style="text-align: left;">
                <b><?= __('Invoice To') ?></b>
            </td>
            <td style="text-align: right;">
                <b><?= __('Invoice from') ?></b>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;"><?= $soldData['customer_name'] ?></td>
            <td style="text-align: right;"><?= $invoiceData['invoice_name'] ?></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: right;">
                <?= __('Tax Number: ') . $invoiceData['tax_number'] ?>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;">
                <b><?= __('Credit Memo') ?></b>
            </td>
            <td style="text-align: right;">
                <?= $invoiceData['address_line1'] . ', ' . $invoiceData['address_line2'] ?>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;">
                <?= __('Credit Memo #: ') . $totals['increment_id']; ?>
            </td>
            <td style="text-align: right;">
                <?= $invoiceData['city'] . ', ' . $invoiceData['post_code'] . ', ' . $invoiceData['region_name'] ?>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;">
                <?= __('Order #: ') . $orderData['increment_id'] ?>
            </td>
            <td style="text-align: right;">
                <?= $invoiceData['country_name'] ?>
            </td>
        </tr>
        <tr>
            <td style="text-align: left;">
                <?= __('Order Date: ') . $orderData['date'] ?>
            </td>
        </tr>
    </table>

    <!--SOLD AND SHIP-->
    <div style="margin-top: 30px;"></div>
    <table class="sold-ship" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif;">
        <tr style="background-color: #F6F6F8;">
            <td style="text-align: left; padding: 10px;">
                <b><?= __('Sold To') ?></b>
            </td>
            <?php if ($shippingData): ?>
                <td style="text-align: left; padding: 10px;">
                    <b><?= __('Ship To') ?></b>
                </td>
            <?php else: ?>
                <td style="text-align: left; padding: 10px;">
                    <b><?= __('Payment Method') ?></b>
                </td>
            <?php endif; ?>
        </tr>
        <tr>
            <td style="text-align: left; padding-top: 15px; padding-left: 10px;"><?= $soldData['customer_name'] ?></td>
            <?php if ($shippingData): ?>
                <td style="text-align: left; padding-top: 15px; padding-left: 10px;"><?= $shippingData['customer_name'] ?></td>
            <?php else: ?>
                <?php if(!isset($orderData['payment']['of_payment'])): ?>
                    <td style="text-align: left; padding-left: 10px; padding-top: 15px;line-height: 1.3;"><?= $orderData['payment'][0] ?></td>
                <?php else: ?>
                    <td style="text-align: left; padding-left: 10px; padding-top: 15px; line-height: 1.3;"><?= $orderData['payment']['of_payment'][0] ?></td>
                <?php endif; ?>
            <?php endif; ?>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= $soldData['street'] ?></td>
            <?php if ($shippingData): ?>
                <td style="text-align: left; padding-left: 10px;"><?= $shippingData['street'] ?></td>
            <?php else: ?>
                <?php if(!isset($orderData['payment']['of_payment'])): ?>
                    <td style="text-align: left; padding-left: 10px;"><?= $orderData['payment'][1] ?></td>
                <?php else: ?>
                    <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                <?php endif; ?>
            <?php endif; ?>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= $soldData['city'] ?></td>
            <?php if ($shippingData): ?>
                <td style="text-align: left; padding-left: 10px;"><?= $shippingData['city'] ?></td>
            <?php else: ?>
                <?php if(!isset($orderData['payment']['of_payment'])): ?>
                    <td style="text-align: left; padding-left: 10px;"><?= $orderData['payment'][2] ?></td>
                <?php else: ?>
                    <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                <?php endif; ?>
            <?php endif; ?>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= $soldData['country'] ?></td>
            <?php if ($shippingData): ?>
                <td style="text-align: left; padding-left: 10px;"><?= $shippingData['country'] ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= __('T: ') . $soldData['telephone'] ?></td>
            <?php if ($shippingData): ?>
                <td style="text-align: left; padding-left: 10px;"><?= __('T: ') . $shippingData['telephone'] ?></td>
            <?php endif; ?>
        </tr>
    </table>

    <!--PAYMENT AND SHIPPING-->
    <?php if ($shippingData): ?>
        <div style="margin-top: 30px;"></div>
        <table class="payment-ship" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif;">
            <tr style="background-color: #F6F6F8;">
                <td style="text-align: left; padding: 10px;">
                    <b><?= __('Payment Method') ?></b>
                </td>
                <td style="text-align: left; padding: 10px;">
                    <b><?= __('Shipping Method') ?></b>
                </td>
            </tr>
            <tr>
                <?php if(!isset($orderData['payment']['of_payment'])): ?>
                    <td style="text-align: left; padding-left: 10px; padding-top: 15px;line-height: 1.3;"><?= $orderData['payment'][0] ?></td>
                <?php else: ?>
                    <td style="text-align: left; padding-left: 10px; padding-top: 15px; line-height: 1.3;"><?= $orderData['payment']['of_payment'][0] ?></td>
                <?php endif; ?>
                    <td style="text-align: left; padding-left: 10px; padding-top: 15px; line-height: 1.3;"><?= $orderData['shipment']['shipping_method'] ?></td>
            </tr>
            <tr>
                <?php if(!isset($orderData['payment']['of_payment'])): ?>
                    <td style="text-align: left; padding-left: 10px;"><?= $orderData['payment'][1] ?></td>
                <?php else: ?>
                    <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                <?php endif; ?>
            </tr>
            <tr>
                <?php if(!isset($orderData['payment']['of_payment'])): ?>
                    <td style="text-align: left; padding-left: 10px;"><?= $orderData['payment'][2] ?></td>
                <?php else: ?>
                    <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                <?php endif; ?>
                    <td style="text-align: left; padding-left: 10px;"><?= $orderData['shipment']['shipping_total'] ?></td>
            </tr>
        </table>
    <?php endif; ?>

    <!--ORDER ITEMS-->
    <div style="margin-top: 30px;"></div>
    <table class="order-item" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-family: Arial, Helvetica, sans-serif; font-size: 13px;">
        <tr style="line-height: 20px; background-color: #F6F6F8; font-weight: bold;">
            <td style="width: 23%; text-align: left;"><?= __('Products') ?></td>
            <td style="width: 17%; text-align: left;"><?= __('SKU') ?></td>
            <td style="width: 15%; text-align: right"><?= __('Total(ex)') ?></td>
            <td style="width: 15%; text-align: right"><?= __('Discount') ?></td>
            <td style="width: 6%; text-align: right"><?= __('Qty') ?></td>
            <td style="width: 12%; text-align: right"><?= __('Tax') ?></td>
            <td style="width: 12%; text-align: right"><?= __('Subtotal') ?></td>
        </tr>
        <?php foreach ($orderItems as $orderItem): ?>
            <?php if (!$vendorInfo['vendor_id']  && $orderItem->getQtyRefunded() > 0 ):?>
                <?php if ($orderItem->getProductType() == "configurable"): ?>
                    <?php $childItems = $orderItem->getChildrenItems(); ?>
                    <?php foreach ($childItems as $item): ?>
                        <tr>
                            <td style="width: 23%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $item->getName() ?></td>
                            <td style="width: 17%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $item->getSku() ?></td>
                            <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded()) ?></td>
                            <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getDiscountAmount()) ?></td>
                            <td style="width: 6%; text-align: right"><?= $item->getQtyRefunded() * 1 ?></td>
                            <td style="width: 12%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getTaxAmount()) ?></td>
                            <td style="width: 12%; text-align: right">
                                <?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded() + $orderItem->getTaxAmount() + $orderItem->getDiscountTaxCompensationAmount() - $orderItem->getDiscountAmount()) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td style="width: 23%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $orderItem->getName() ?></td>
                        <td style="width: 17%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $orderItem->getSku() ?></td>
                        <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded()) ?></td>
                        <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getDiscountAmount()) ?></td>
                        <td style="width: 6%; text-align: right"><?= $orderItem->getQtyRefunded() * 1 ?></td>
                        <td style="width: 12%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getTaxAmount()) ?></td>
                        <td style="width: 12%; text-align: right">
                            <?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded() + $orderItem->getTaxAmount() + $orderItem->getDiscountTaxCompensationAmount() - $orderItem->getDiscountAmount()) ?>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php else: ?>
                <?php if ($vendorInfo['vendor_id'] == $orderItem->getVendorId()): ?>
                    <?php if ($orderItem->getProductType() == "configurable"): ?>
                        <?php $childItems = $orderItem->getChildrenItems(); ?>
                        <?php foreach ($childItems as $item): ?>
                            <tr>
                                <td style="width: 23%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $item->getName() ?></td>
                                <td style="width: 17%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $item->getSku() ?></td>
                                <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded()) ?></td>
                                <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getDiscountAmount()) ?></td>
                                <td style="width: 6%; text-align: right"><?= $item->getQtyRefunded() * 1 ?></td>
                                <td style="width: 12%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getTaxAmount()) ?></td>
                                <td style="width: 12%; text-align: right">
                                    <?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded() + $orderItem->getTaxAmount() + $orderItem->getDiscountTaxCompensationAmount() - $orderItem->getDiscountAmount()) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td style="width: 23%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $orderItem->getName() ?></td>
                            <td style="width: 17%; text-align: left; word-wrap: break-word; line-height: 20px;"><?= $orderItem->getSku() ?></td>
                            <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded()) ?></td>
                            <td style="width: 15%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getDiscountAmount()) ?></td>
                            <td style="width: 6%; text-align: right"><?= $orderItem->getQtyRefunded() * 1 ?></td>
                            <td style="width: 12%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($orderItem->getTaxAmount()) ?></td>
                            <td style="width: 12%; text-align: right">
                                <?= $mcmHelper->formatToBaseCurrency($orderItem->getAmountRefunded() + $orderItem->getTaxAmount() + $orderItem->getDiscountTaxCompensationAmount() - $orderItem->getDiscountAmount()) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>

    <!--FOOTER TOTAL-->
    <div style="margin-top: 30px;"></div>
    <table cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; display: inline-table; border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; font-size: 13px;">
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8; padding-top: 15px;">
                <b><?= __('Subtotal:') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8; padding-top: 15px;">
                <b><?= $mcmHelper->formatToBaseCurrency($totals['subtotal']) ?></b>
            </td>
        </tr>
            <tr>
                <td style="width: 50%"></td>
                <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                    <b><?= __('Adjustment Fee:') ?></b>
                </td>
                <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                    <b><?= $mcmHelper->formatToBaseCurrency($totals['adjustment_negative']) ?></b>
                </td>
            </tr>
            <tr>
                <td style="width: 50%"></td>
                <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                    <b><?= __('Rewards Discount:') ?></b>
                </td>
                <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                    <b><?= $mcmHelper->formatToBaseCurrency($block->getData('reward_discount')) ?></b>
                </td>
            </tr>
        <?php if ($totals['discount_amount'] != 0): ?>
            <tr>
                <td style="width: 50%"></td>
                <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                    <b><?= __('Discount:') ?></b>
                </td>
                <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                    <b><?= $mcmHelper->formatToBaseCurrency($totals['discount_amount']) ?></b>
                </td>
            </tr>
        <?php endif; ?>
        <?php if ($totals['tax_amount'] != 0): ?>
            <tr>
                <td style="width: 50%"></td>
                <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                    <b><?= __('Tax:') ?></b>
                </td>
                <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                    <b><?= $mcmHelper->formatToBaseCurrency($totals['tax_amount']) ?></b>
                </td>
            </tr>
        <?php endif; ?>
        <tr>
            <td style="width: 50%"></td>
            <td colspan="2" style="padding-left: 10px; padding-right: 10px; background-color: #F6F6F8;">
                <hr style="border-bottom: solid 2px #ebebef;">
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8; padding-bottom: 15px;">
                <b><?= __('Grand Total:') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8; padding-bottom: 15px;">
                <b><?= $mcmHelper->formatToBaseCurrency($totals['grand_total']) ?></b>
            </td>
        </tr>
    </table>
</body>
