<?php
/** @var \Mirasvit\GoogleTagManager\Block\Render $block */

use Mirasvit\Core\Service\SerializeService;

$data = $block->getDataLayerData();
?>
<script>
    window.dataLayer = window.dataLayer || [];
    window.mstGtmProducts = window.mstGtmProducts || [];

    <?php foreach ($data as $item): ?>
        window.dataLayer.push({ecommerce: null});

        <?php if ($item && isset($item['ecommerce'])): ?>
            window.dataLayer.push(<?=SerializeService::encode($item) ?>);
        <?php else: ?>
            if (typeof gtag != 'undefined') {
                gtag("<?= $item[0]?>", "<?= $item[1]?>", <?= SerializeService::encode($item[2])?>);
            } else {
                window.dataLayer.push({"<?= $item[0]?>": "<?= $item[1]?>", ecommerce: <?= SerializeService::encode((object)$item[2])?>});
            }
        <?php endif; ?>

    <?php endforeach ?>

    window.mstGtmProducts = <?= SerializeService::encode($block->getDataLayerProducts()); ?>;
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "mst_gtm_product_storage": {
                        "component": "Mirasvit_GoogleTagManager/js/product-storage",
                        "itemInfoUrl": "<?= $block->getItemInfoUrl() ?>"
                    },
                    "mst_gtm": {
                        "component": "Mirasvit_GoogleTagManager/js/layer"
                    },
                    "mst_gtm_events": {
                        "component": "Mirasvit_GoogleTagManager/js/events"
                    },
                    "mst_gtm_toolbar": {
                        "component": "Mirasvit_GoogleTagManager/js/toolbar"
                    }
                }
            }
        }
    }
</script>
