<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattr
 */
?>
<?php
/**
 * @var \Amasty\Orderattr\Block\Order\Attributes $block
 */
?>

<?php if ($orderAttributeList = $block->getOrderAttributesData()): ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $block->escapeHtml(__('Additional Information:')); ?>
            </th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($orderAttributeList as $attribute): ?>
            <tr>
                <td valign="top"><label><?= $block->escapeHtml(__($attribute['label'])); ?></label></td>
                <td>
                    <?php if (is_array($attribute['value'])): ?>
                        <a class="file-link" target="_blank" href="<?= /** @noEscape */ $attribute['value']['url'] ?? '' ?>">
                            <?= /** @noEscape */ $attribute['value']['name'] ?? ''; ?>
                        </a>
                    <?php else: ?>
                        <?= /** @noEscape */ $attribute['value']; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="2"></td>
        </tr>
        </tbody>
    </table>
<?php endif; ?>

