<?php
$courier = $block->getRequest()->getParam('courier', '');
$sourceStockId = $block->getRequest()->getParam('source_stock_id', 0);
$collection = $block->getShipmentList($courier, $sourceStockId);
$sourceData = $block->getSourceDetail($sourceStockId);
$urlGetSlots = $block->getUrl("omnyfy_easyship/bookPickup/ajaxGetPickupSlot");
$urlBookPickup = $block->getUrl("omnyfy_easyship/bookPickup/ajaxBookPickup");
$urlMarkHandedOver = $block->getUrl("omnyfy_easyship/bookPickup/ajaxMarkHandedOver");
$urlCancelShipment = $block->getUrl("omnyfy_easyship/shipment/ajaxCancelShipment");
$shipBlock = $block->getLayout()->createBlock('Omnyfy\Easyship\Block\Adminhtml\Order\ShipmentCreate');
?>

<div class="content">
    <table class="data-table admin__table-secondary">
        <thead>
            <tr>
                <td><b>Select</b></td>
                <td><b>Order #</b></td>
                <td><b>Shipping Id</b></td>
                <td><b>Customer Name</b></td>
                <td><b>Delivery Address</b></td>
                <td><b>Country</b></td>
                <td><b>Items</b></td>
                <td><b>Shipment Status</b></td>
                <td><b>Pickup Reference</b></td>
                <td><b>Track Shipment</b></td>
                <td><b>Cancel Shipment</b></td>
            </tr>
        </thead>
        <tbody id="courier_order_list">
            <?php if(count($collection) > 0):?>
                <?php foreach($collection as $ship): ?>
                    <?php
                        $order = $block->getOrder($ship->getOrderId());
                        $address = $order->getShippingAddress()->getData();
                        $pickupReference = $block->getPickupReferenceByShipmentId($ship->getEasyshipShipmentId());
                        $disabled = "";
                        if ($pickupReference != 'Pending' || $ship->getStatus() == 'cancelled') {
                            $disabled = 'disabled';
                        }
                    ?>

                    <tr>
                        <td><input type="checkbox" name="selected_order[]" value="<?= $ship->getEasyshipShipmentId()?>" <?= $disabled;?>/></td>
                        <td><?= $order->getIncrementId()?></td>
                        <td><?= $ship->getEasyshipShipmentId()?></td>
                        <td><?= $ship->getDestinationName()?></td>
                        <td><?= $address['street'].', '.$address['city'].', '.$address['region'].', '. $address['postcode'] ?></td>
                        <td><?= $address['country_id']?></td>
                        <td><?= $ship->getCountItems()?></td>
                        <td><?= ucfirst($ship->getStatus())?></td>
                        <td><?= $pickupReference?></td>
                        <td>
                            <?php
                                $label = $block->getTrackingDetailByShipmentId($ship->getEasyshipShipmentId());
                                if ($label != null){
                                    if($label->getTrackingPageUrl() != null){ ?>
                                        <a href="#"
                                        data-mage-init='{"popupWindow": {"windowURL":"<?= $label->getTrackingPageUrl() ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
                                        title="<?= $block->escapeHtml(__('Track this shipment')) ?>"
                                        class="action track">
                                            <span><?= $label->getTrackingNumber()?></span>
                                        </a>
                                <?php }else{ ?>
                                    <?= $label->getTrackingNumber()?>
                                <?php } ?>
                            <?php } ?>
                        </td>
                        <td>
                        <?php if($ship->getStatus() != 'cancelled'){ ?>
                            <button class="primary cancel_shipment"
                                data-locationid="<?= $ship->getSourceStockId()?>"
                                data-easyshipshipmentid="<?= $ship->getEasyshipShipmentId()?>">
                            <?= $block->escapeHtml(__('Cancel Shipment')) ?>
                            </button>
                        <?php } ?>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>

<div id="pickup_time_popup">
    <h3>Select Pickup Date and Time</h3>
    <p id="title_locationname">Pickup From: <?= $sourceData->getName()?></p>
    <table class="data-table admin__table-secondary">
        <tbody id="pickup_time_list"></tbody>
    </table>

    <form id="selected_pickup_time" name="selected_pickup_time" method="POST" data-mage-init='{"validation": {}}'>
        <input type="hidden" id="frm_preferred_date" name="preferred_date" />
        <input type="hidden" id="frm_preferred_maxtime" name="preferred_maxtime" />
        <input type="hidden" id="frm_preferred_mintime" name="preferred_mintime" />
    </form>
</div>

<script type="text/javascript">// <![CDATA[
require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],
    function($, modal) {
        $(document).ready(function() {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Confirm Pickup Date and Time'),
                    class: 'mymodal1',
                    click: function () {
                        if ($('#frm_preferred_date').val() == "") {
                            alert('Please select a slot');
                            return false;
                        }
                        var shipmentIds = "";
                        $('input[name="selected_order[]"]:checked').each(function() {
                            shipmentIds += this.value + ",";
                        });

                        var formdata = new FormData($('#selected_pickup_time')[0]);
                        formdata.append("form_key", window.FORM_KEY);
                        formdata.append("courier_id", '<?= $courier ?>');
                        formdata.append("source_stock_id", <?= $sourceStockId ?>);
                        formdata.append("shipment_ids", shipmentIds);

                        $.ajax({
                            method: "POST",
                            url: "<?= $urlBookPickup; ?>",
                            dataType: "json",
                            data: formdata,
                            showLoader: true,
                            processData: false,
                            contentType: false,
                            success: function(response){
                                console.log(response);
                                location.reload();
                            },
                            error: function () {
                                alert('Something went wrong. Please try again.');
                            }
                        });
                    }
                }]
            };
            var popup = modal(options, $('#pickup_time_popup'));

            $('#easyship_book_pickup').click(function(){
                var atLeastOneIsChecked = $('input[name="selected_order[]"]:checked').length > 0;

                if (atLeastOneIsChecked) {
                    $('#pickup_time_list').html('');
                    $('#frm_preferred_date').val('');
                    $('#frm_preferred_mintime').val('');
                    $('#frm_preferred_maxtime').val('');

                    var slothtml = "";

                    $.ajax({
                        method: "GET",
                        url: "<?= $urlGetSlots; ?>",
                        dataType: "json",
                        data: {
                            courier_id: "<?= $courier ?>",
                            source_stock_id: <?= $sourceStockId ?>
                        },
                        showLoader:true,
                        success: function(response){
                            if(response.error){
                                location.reload();
                                return false;
                            }
                            if (response.data != null) {
                                $("#pickup_time_popup").modal("openModal");
                                var slotdata = response.data.pickup.slots;
                                var counter = 0
                                $.each(slotdata, function(key, value) {
                                    slothtml += '<tr>';
                                    slothtml += '<td>'+key+'</td>';
                                    slothtml += '<td>';
                                    if (value.length > 0) {
                                        for (let index = 0; index < value.length; index++) {
                                            slothtml += '<div class="admin__field-control"><div class="admin__field admin__field-option">';
                                            slothtml += '<input type="radio" name="radio_pickup_slot" class="admin__control-radio" id="radio_pickup_'+counter+'" data-date="'+key+'" data-mintime="'+value[index].min_time+'" data-maxtime="'+value[index].max_time+'" />';
                                            slothtml += '<label class="admin__field-label" for="radio_pickup_'+counter+'"> '+value[index].min_time+':00 - '+value[index].max_time+':00</label>';
                                            slothtml += '</div></div>';
                                            counter++;
                                        }
                                    }
                                    slothtml += '</td>';
                                    slothtml += '</tr>'; 
                                });
                            }
                            $('#pickup_time_list').append(slothtml);
                        }
                    });
                }else{
                    alert('Please select an order');
                }
            });

            $('#mark_handed_over').click(function(){
                var atLeastOneIsChecked = $('input[name="selected_order[]"]:checked').length > 0;

                if (atLeastOneIsChecked) {
                    var shipmentIds = "";
                    $('input[name="selected_order[]"]:checked').each(function() {
                        shipmentIds += this.value + ",";
                    });

                    $.ajax({
                        method: "POST",
                        url: "<?= $urlMarkHandedOver; ?>",
                        dataType: "json",
                        data: {
                            form_key: window.FORM_KEY,
                            source_stock_id: <?= $sourceStockId ?>,
                            shipment_ids: shipmentIds
                        },
                        showLoader: true,
                        success: function(response){
                            console.log(response);
                            location.reload();
                        },
                        error: function () {
                            alert('Something went wrong. Please try again.');
                        }
                    });
                }else{
                    alert('Please select an order');
                }
            });

            $('#courier_order_list').on('click', 'tr', function(event) {
                if (event.target.type !== 'checkbox') {
                    $(':checkbox', this).trigger('click');
                }
            });

            $('#pickup_time_list').on('click', 'tr', function(event) {
                if (event.target.type === 'radio') {
                     var radio_elmt = $('input[name=radio_pickup_slot]:checked', '#pickup_time_list');
                    $('#frm_preferred_date').val(radio_elmt.attr('data-date'));
                    $('#frm_preferred_mintime').val(radio_elmt.attr('data-mintime'));
                    $('#frm_preferred_maxtime').val(radio_elmt.attr('data-maxtime'));
                }
            });

            $('.cancel_shipment').click(function(e){
                e.preventDefault();
                $.ajax({
                    method: "POST",
                    url: "<?= $urlCancelShipment; ?>",
                    dataType: "json",
                    data: {
                        form_key: window.FORM_KEY,
                        source_stock_id: $(this).data("locationid"),
                        easyship_shipment_id: $(this).data("easyshipshipmentid"),
                    },
                    showLoader:true,
                    success: function(response){
                        console.log(response);
                        location.reload();
                    },
                    error: function () {
                        alert('Something went wrong. Please try again.');
                    }
                });
            });
        });
    }
);
// ]]></script>