<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$helper = $this->helper(\OmnyfyCustomzation\Mcm\Helper\Data::class);
$vendor = $helper->getVendor($_item->getVendorId());
$product = $_item->getProduct();
$leadTime = $product->getResource()->getAttribute('lead_time')->getFrontend()->getValue($product);
$largeOrder = $product->getResource()->getAttribute('large_order_lead_time')->getFrontend()->getValue($product);
?>
<tr>
    <td class="col-thumbnail">
        <img src="<?= $helper->getThumbnailItem($product) ?>" alt="<?= $product->getName() ?>"
             width="100"/>
    </td>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="vendor-name"><?= $block->escapeHtml($vendor->getName()) ?></p>
        <p class="product-name">
            <a href="<?= $block->escapeHtml($product->getProductUrl()) ?>" target="_blank"><?= $block->escapeHtml($_item->getName()) ?></a>
        </p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */
                        nl2br($block->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
        <br>
        <?php if ($leadTime): ?>
            <p class="lead-time">
                <b><?= __('MOQ Lead Time: ') ?></b>
            </p>
            <p><?= __($leadTime) ?></p>
        <?php endif; ?>

        <?php if ($largeOrder): ?>
            <p class="lead-time">
                <b><?= __('Large Order Lead Time: ') ?></b>
            </p>
            <p><?= __($largeOrder) ?></p>
        <?php endif; ?>
    </td>
    <td class="item-qty"><?= (int)$_item->getQtyOrdered() ?></td>
    <td class="item-price">
        <?= /* @noEscape */
        $block->getItemPrice($_item) ?>
    </td>
    <td class="item-order-note"><?= $_item->getData('order_note') ?></td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
