<?php
$blockObj= $this->getLayout()->createBlock('Omnyfy\Mcm\Block\Adminhtml\PendingPayouts\View\Tab\PayoutOrders');
?>
<div class="payout-wrapper">
    <div class="payout-row">
        <label class="payout-label">
            <span>Total Payout Amount</span>
        </label>
        <div class="payout-currency" >
            <span><?php echo $block->escapeHtml($block->getTotalPayoutAmount()); ?></span>
        </div>
    </div>
    <div class="payout-row">
        <label class="payout-label">
            <span>Total Fees Charges</span>
        </label>
        <div class="payout-currency">
            <span><?php echo $block->escapeHtml($block->getTotalFeesCharged()); ?></span>
        </div>
    </div>
    <?php if($block->isEnable()): ?>
        <div class="payout-row">
            <label class="payout-label">
                <span>Total Rebates to be received on Payout</span>
            </label>
            <div class="payout-currency">
                <a href="<?= $blockObj->getUrlViewReportRebate() ?>"><span><?php echo $blockObj->escapeHtml($blockObj->getTotalReadyRebate()); ?></span></a>
            </div>
        </div>
    <?php endif; ?>
</div>
