<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$helper = $this->helper(\OmnyfyCustomzation\Mcm\Helper\Data::class);
$vendor = $helper->getVendor($_item->getVendorId());
$product = $_item->getProduct();
?>
<tr er-item-row-<?= (int)$_item->getId() ?>">
<td class="col-thumbnail">
    <img src="<?= $helper->getThumbnailItem($_item->getProduct()) ?>" alt="<?= $_item->getProduct()->getName() ?>"
         width="100">
</td>
<td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
    <p class="vendor-name"><?= $block->escapeHtml($vendor->getName()) ?></p>
    <p class="product-name">
        <a href="<?= $block->escapeHtml($product->getProductUrl()) ?>"
           target="_blank"><?= $block->escapeHtml($_item->getName()) ?></a>
    </p>
    <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
    <?php if ($block->getItemOptions()) : ?>
        <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                <dd>
                    <?= /* @noEscape */
                    nl2br($block->escapeHtml($option['value'])) ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock) : ?>
        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
    <?php endif; ?>
    <?= $block->escapeHtml($_item->getDescription()) ?>
</td>
<td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
    <?= $block->getItemPriceHtml() ?>
</td>
<td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
    <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                <span class="content"><?= (int)$block->getItem()->getQtyOrdered() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                <span class="content"><?= (int)$block->getItem()->getQtyShipped() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                <span class="content"><?= (int)$block->getItem()->getQtyCanceled() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                <span class="content"><?= (int)$block->getItem()->getQtyRefunded() ?></span>
            </li>
        <?php endif; ?>
    </ul>
</td>
<td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
    <?= $block->getItemRowTotalHtml() ?>
</td>
</tr>
