<?php
/** @var OmnyfyCustomzation\ProductPdf\Block\Pdf\Content $block */
$product = $block->getProduct();
$vendor = $block->getVendorByProductId($product->getId());
$technicalPhotos = $block->getTechnicalPhotos($product);
?>
<div class="content">
    <div class="product-photo-container">
        <div class="product-photo">
            <img src="<?= $block->getFullProductImageUrl($product->getImage()) ?>" alt="<?= $product->getName() ?>">
        </div>
        <?php foreach ($technicalPhotos as $photo): ?>
            <div class="technical-drawing">
                <img src="<?= $block->getFullProductImageUrl($photo) ?>"
                     alt="<?= $product->getName() ?>">
            </div>
        <?php endforeach; ?>
    </div>
    <div class="product-info-container">
        <div class="product-vendor" style="height: 300px; overflow: hidden">
            <?php if ($vendor): ?>
                <div class="vendor-name">
                    <span><?= __('Designer: ') ?></span>
                    <span class="name"><?= $vendor->getName() ?></span>
                </div>
            <?php endif; ?>
            <p class="vendor-description"><?= $product->getShortDescription() ?></p>
        </div>

        <div class="hr-content"></div>

        <div class="line-section"></div>
        <div class="product-info">
            <div class="attributes">

                <?php if ($product->getTsDimensionsHeight()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Height (cm):') ?></span>
                        <span class="attribute-value"><?= (float)$product->getTsDimensionsHeight() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getTsDimensionsWidth()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Width (cm):') ?></span>
                        <span class="attribute-value"><?= (float)$product->getTsDimensionsWidth() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getTsDimensionsLength()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Length (cm):') ?></span>
                        <span class="attribute-value"><?= (float)$product->getTsDimensionsLength() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getPrimaryMaterial()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Primary Material:') ?></span>
                        <span class="attribute-value"><?= $block->getProductAttributeText($product, 'primary_material') ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getColor()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Primary Color:') ?></span>
                        <span class="attribute-value"><?= $block->getProductAttributeText($product, 'color') ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getHasOptions()): ?>
                    <?php $productOptions = $block->getProductOptions($product) ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Available Variants:') ?></span>
                        <span class="attribute-value">
                        <?php foreach ($productOptions as $option): ?>
                            <span class="variants"><?= __($option['label']) . ': ' ?></span>
                            <?= $block->getVariations($option) ?>
                        <?php endforeach; ?>
                    </span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getCustomization()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Customization:') ?></span>
                        <span class="attribute-value"><?= $product->getCustomization() ?></span>
                    </div>
                <?php endif; ?>
            </div>

            <div class="product-lighting">
                <?php if ($product->getVoltage()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Voltage:') ?></span>
                        <span class="attribute-value"><?= $product->getVoltage() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getNumberOfBulbs()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Number of Bulbs:') ?></span>
                        <span class="attribute-value"><?= $product->getNumberOfBulbs() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getBulbType()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Bulb Type:') ?></span>
                        <span class="attribute-value"><?= $product->getBulbType() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($block->getProductAttributeText($product, 'bulb_supplied')): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Bulb Supplied:') ?></span>
                        <span class="attribute-value"><?= $block->getProductAttributeText($product, 'bulb_supplied') ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($product->getMaxWattage()): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Max Wattage:') ?></span>
                        <span class="attribute-value"><?= $product->getMaxWattage() ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($block->getProductAttributeText($product, 'shade_included')): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Shade Included:') ?></span>
                        <span class="attribute-value"><?= $block->getProductAttributeText($product, 'shade_included') ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($block->getProductAttributeText($product, 'dimmable')): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Dimmable:') ?></span>
                        <span class="attribute-value"><?= $block->getProductAttributeText($product, 'dimmable') ?></span>
                    </div>
                <?php endif; ?>

                <?php if ($block->getProductAttributeText($product, 'certifications')): ?>
                    <div class="attribute">
                        <span class="attribute-label"><?= __('Certifications:') ?></span>
                        <span class="attribute-value"><?= $block->getProductAttributeText($product, 'certifications') ?></span>
                    </div>
                <?php endif; ?>

            </div>

        </div>
    </div>
    <div class="clear"></div>
</div>
<style>
    .clear {
        display: block;
        clear: both;
    }
    .product-photo-container {
        float: left;
        width: 50%;
    }
    .product-info-container {
        float: right;
        width: 50%;
    }
    .content {
        font-family: 'Rasa', serif;
        font-size: 12pt;
    }

    .product-vendor, .product-info, .line-section {
        padding-left: 15px;
    }

    .technical-drawing {
        padding-top: 15px;
    }

    .vendor-name {
        font-size: 16px;
        font-weight: bold;
        margin-bottom: 5px;
    }

    .vendor-name .name {
        text-transform: uppercase;

    }

    .vendor-description * {
        font-size: 12px;
        text-align: justify;
    }

    .attributes .attribute-label {
        font-weight: bold;
    }

    .product-info {
        text-align: left;
    }

    .product-lighting {
        margin-top: 20px;
    }

    .product-lighting .attribute-label {
        font-weight: bold;
        color: #555
    }

</style>
