<?php
/** @var OmnyfyCustomzation\ProductPdf\Block\Pdf\Header $block */
$product = $block->getProduct();
?>

<div id="header" class="header">
    <div class="logo">
        <div class="">
            <?php if ($block->getStoreLogo()): ?>
                <img class="img-responsive" src="<?php echo $block->getStoreLogo(); ?>" alt="Store Logo"/>
            <?php endif; ?>
        </div>
    </div>
    <div class="product-header-container">
        <div class="product-header">
            <h3 class="product-name"><b><?= $product->getName() ?></b></h3>
            <h3 class="product-sku"><?= __('SKU: %1', $product->getSku()) ?></h3>
        </div>
    </div>
    <div class="clear"></div>
</div>
<div class="hr"></div>

<style>
    .header {
        font-family: 'Rasa', sans-serif;
        font-size: <?php echo $block->getConfig('header_fontsize'); ?>;
        color: #<?php echo $block->getConfig('header_fontcolor'); ?>;
    }

    .header .store-title {
        font-family: <?php echo $block->getStoreTitleFontFamily(); ?>;
        font-size: <?php echo $block->getConfig('store_title_fontsize'); ?>;
        color: #<?php echo $block->getConfig('store_title_color'); ?>;
    }

    div.hr {
        background-color: #<?php echo $block->getConfig('bottomline_color'); ?>;
        height: <?php echo $block->getConfig('bottomline_thickness'); ?>;
        margin-bottom: 20px;
    }

    div.hr-content {
        background-color: #<?php echo $block->getConfig('bottomline_color'); ?>;
        height: <?php echo $block->getConfig('bottomline_thickness'); ?>;
        margin: 0 0 20px 15px;
        width: 100%;
    }

    .product-info {
        text-align: right;
    }

    .logo {
        float: left;
        width: 50%;
    }

    .product-header-container {
        float: right;
        width: 50%;
    }

    .clear {
        clear: both;
    }

    .product-name {
        text-transform: uppercase;
        font-weight: 700!important;
    }

    h3.product-sku {
        font-size: 16px;
        font-weight: normal;
    }

    .img-responsive {
        width: 300px;
    }

    .description-content {
        padding: 0 50px;
        text-align: center;
    }
    .product-header{
        text-align: right;
    }

</style>
