<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Gdpr
 */
?>
<?php /** @var \Amasty\Gdpr\Block\PolicyPopup $block */ ?>
<?php if ($block->showOnPageLoad()): ?>
    <!-- ko scope: 'gdpr-privacy-container' -->
    <div data-role="gdpr-privacy-container" class="amgdpr-privacy-policy">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <!-- /ko -->

    <script type="text/x-magento-init">
    {
        "[data-role=gdpr-privacy-container]": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "gdpr-privacy-container": {
                        "component": "Amasty_Gdpr/js/policy-popup",
                        "template": "Amasty_Gdpr/policy-popup",
                        "textUrl": "<?= $block->escapeUrl($block->getTextUrl()); ?>",
                        "acceptUrl": "<?= $block->escapeUrl($block->getAcceptUrl()); ?>",
                        "popupDataUrl": "<?= $block->escapeUrl($block->getPopupDataUrl()); ?>"
                    }
                }
            }
        }
    }
</script>
<?php endif; ?>
