<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Gdpr
 */
?>
<?php
/** @var $block \Amasty\Gdpr\Block\Settings */
/** @var \Magento\Framework\Escaper $escaper */

$settings = $block->getPrivacySettings();
?>
<?php foreach ($settings as $setting): ?>
    <div class="block">
        <div class="block-title"><strong><?= $escaper->escapeHtml($setting['title']) ?></strong></div>
        <div class="block-content amgdpr-block-content">
        <?php if (isset($setting['action'])): ?>
            <form method="post"
                  action="<?= $escaper->escapeUrl($setting['action']) ?>"
                  data-mage-init='{"validation":{}}'>
                <input name="form_key" type="hidden" value="<?= /* @noEscape */ $block->getFormKey(); ?>" />
                <p class="policy-content"><?= /* @noEscape */ $setting['content'] ?></p>
                <?php if ($setting['hasCheckbox']): ?>
                    <p class="field control checkbox">
                        <input type="checkbox"
                               id="amgdpr-<?= $escaper->escapeHtmlAttr($setting['actionCode']) ?>"
                               data-validate="{required:true}"
                               name="agree"/>
                        <label class="accept addon" for="amgdpr-<?= $escaper->escapeHtmlAttr($setting['actionCode']) ?>">
                            <?= $escaper->escapeHtml($setting['checkboxText']) ?>
                        </label>
                    </p>
                <?php endif; ?>
                <?php if (isset($setting['additionalBlock'])
                    && $setting['additionalBlock'] instanceof \Magento\Framework\View\Element\AbstractBlock
                ): ?>
                <p class="control">
                    <?= /* @noEscape */ $setting['additionalBlock']->toHtml(); ?>
                </p>
                <?php endif; ?>
                <?php if ($setting['needPassword']): ?>
                    <fieldset class="fieldset" data-hasrequired="* Required Fields" <?php if ($setting['hidePassword']): ?> hidden <?php endif; ?> name="passwordField">
                        <div class="field password current required">
                            <label class="label" for="current-password">
                                <span><?= $escaper->escapeHtml(__('Current Password')) ?></span>
                            </label>
                            <div class="control">
                                <input type="password" class="input-text" name="current_password" id="current-password-<?= /* @noEscape */ $setting['actionCode'] ?>" data-input="current-password" autocomplete="off" aria-required="true" data-validate="{required:true}">
                            </div>
                        </div>
                    </fieldset>
                <?php endif; ?>
                <div class="actions-toolbar amgdpr-actions-toolbar">
                    <button type="submit" class="action primary">
                        <?= $escaper->escapeHtml($setting['submitText']) ?>
                    </button>
                </div>
            </form>
        <?php elseif (isset($setting['policiesText'])): ?>
            <div data-role="amasty-gdpr-consent">
                <a href="#" title="<?= $escaper->escapeHtmlAttr(__('Read Privacy Policy')) ?>">
                    <?= $escaper->escapeHtml(__('Read Privacy Policy')) ?>
                </a>
            </div>
            <?php if ($setting['isCookieEnabled']): ?>
                <div class="amgdpr-cookie-link">
                    <a href="#" class="amgdpr-link" data-amgdpr-js="cookie-link" title="<?= $escaper->escapeHtmlAttr(__('Read Cookie Policy')) ?>">
                        <?= $escaper->escapeHtml(__('Read Cookie Policy')) ?>
                    </a>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <p class="policy-content"><?= /* @noEscape */ $block->stripHtmlTags($setting['content'], ['script']) ?></p>
        <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>

<script type="text/x-magento-init">
    {"*": {
            "Amasty_Gdpr/js/show-password": {}
          }
    }
</script>
