<?php
/**
 *  @var \Omnyfy\Enquiry\Block\Customer\View $block
 */
?>
<?php $enquiry = $block->getEnquiry();?>
<?php $vendor = $block->getVendor($enquiry->getVendorId());?>
<?php $mainMessage = $block->getMessages($enquiry->getId(),null,1)?>
<?php $allMessasages = $block->getMessages($enquiry->getId(),$mainMessage[0]['enquiry_messages_id'],null)?>
<?php $vendorUrl = $block->getUrl('shop/brands/view',['id' => $vendor->getId()])?>

<div class="page-sub-title">
    <?php echo $block->escapeHtml($vendor->getName())?> <?php if($enquiry->getProductId()) echo '| '.$block->getProductName($enquiry->getProductId())?>
</div>

<div class="enquiry-communication">

</div>

<div class="messages-list" id="enquiry-messages">
    <div class="customer-sent">
        <div class="message-box">
            <div class="date">
                <?php echo $block->getFrontendDate($enquiry->getUpdatedDate())?>
            </div>
            <div class="message">
                <p><?php echo $block->escapeHtml($mainMessage[0]['message'])?></p>
            </div>
        </div>
    </div>
	<?php foreach($allMessasages as $message):?>
		<?php if($message['from_type']=='vendor' && $message['is_visible_frontend']=='1'){?>
			<div class="vendor-sent">
                <div class="message-box">
                    <div class="info">
                        <a href="<?php echo $vendorUrl?>" class="name"><?php echo $vendor->getName()?></a>
                        <span class="date">Responded on <?php echo $block->getFrontendDate($message['send_time'])?></span>
                    </div>
                    <div class="message">
                        <p><?php echo $block->escapeHtml($message['message'])?></p>
                    </div>
                </div>
			</div>
		<?php }?>

		<?php if($message['from_type']=='customer'){?>
            <div class="customer-sent">
                <div class="message-box">
                    <div class="date"><?php echo $block->getFrontendDate($message['send_time'])?></div>
                    <div class="message">
                        <p><?php echo $block->escapeHtml($message['message'])?></p>
                    </div>
                </div>
            </div>
		<?php }?>
	<?php endforeach;?>
</div>
<div class="reply-field-container">
	<div id="message-complete" style="display:none"></div>
	<div class="form-group">
		<label for="reply-message" class="sr-only">Message</label>
		<textarea class="form-control" name="reply-message" rows="4" required></textarea>
	</div>
	<div class="actions">
		<button class="action" id="cancel-btn"><?= __('Cancel')?></button>
		<button class="action primary" id="reply-btn"><?= __('Submit')?></button>
	</div>
	<div class="controllers" style="display:none;">
		<input type="hidden" name="enquiry-id" value="<?php echo $enquiry->getId()?>" />
		<input type="hidden" name="vendor-id" value="<?php echo $enquiry->getVendorId()?>" />
		<input type="hidden" name="customer-id" value="<?php echo $enquiry->getCustomerId()?>" />
		<input type="hidden" name="customer-email" value="<?php echo $vendor->getEmail() ?>" />
		<input type="hidden" name="product-id" value="<?php echo $block->getProductId()?>" />
		<input type="hidden" name="from_type" value="<?php echo \Omnyfy\Enquiry\Helper\Data::CUSTOMER_TYPE ?>" />
		<input type="hidden" name="to_type" value="<?php echo \Omnyfy\Enquiry\Helper\Data::VENDOR_TYPE ?>" />
		<input type="hidden" name="ajax-url" value="<?php echo $block->getReplyAjaxUrl() ?>" />
	</div>
</div>

<script id="customer-conversation" type="text/x-magento-template">
    <div class="customer-sent">
		<div class="message-box">
			<div class="date"><%- data.title %></div>
			<div class="message">
				<p><%- data.message %></p>
			</div>
		</div>
    </div>
</script>
<script type="text/javascript">
require(['jquery'],function($){
	jQuery(".account-nav .item").each(function(){
		if(jQuery(this).text()=='My Enquiries'){
			jQuery(this).html('<li class="nav item current"><a href="<?php echo $this->getUrl('enquiry/customer')?>"><strong>My Enquiries</strong></a></li>');
		}
	});
});
</script>
