<?php
/**
* @var $block \Omnyfy\Enquiry\Block\Location\View\Form
 */
?>
<?php
$locationId = $this->getRequest()->getParam('id');
$vendorId = $this->helper('\Omnyfy\Enquiry\Helper\Data')->getVendorIdByLocationId($locationId);

if($this->helper('\Omnyfy\Enquiry\Helper\Data')->isEnabled($vendorId)){
    $displayBlock = null;
    $displayNone = null;
    if (strpos($block->getRedirectedUrl(), 'referer') !== false) {
        $displayBlock = 'style="display:block;"';
        $displayNone = 'style="display:none;"';
    }?>
    <?php if($block->isLoggedIn()): ?>

        <form data-mage-init='{"validation":{}}' class="form contact-omnyfy enquiry-form" action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>" id="enquiry-form1" method="post" novalidate="novalidate">
            <!--data-hasrequired="<?php /* @escapeNotVerified */ //echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}' -->
            <?php echo $block->getBlockHtml('formkey'); ?>
            <input type="hidden" name="location_id" value="<?php echo $this->getRequest()->getParam('id');?>" />
            <div class="row-group">
                <div class="enquiry-form-row">
                    <div class="field-wrapper">
                        <div class="form-group">
                            <label for="firstname" class="sr-only">First Name</label>
                            <input placeholder="First Name" type="text" class="validate-alpha" data-validate="{required:true}" data-msg-required="Please enter a valid First Name." id="firstname" name="firstname"> <!--validate-alpha-->
                        </div>
                    </div>
                    <div class="field-wrapper">
                        <div class="form-group">
                            <label for="lastname" class="sr-only">Last Name</label>
                            <input placeholder="Last Name" type="text" class="validate-alpha" data-validate="{required:true}" data-msg-required="Please enter a valid Last Name." id="lastname" name="lastname"><!--validate-alpha-->
                        </div>
                    </div>
                </div>
                <div class="enquiry-form-row">
                    <div class="field-wrapper">
                        <div class="form-group">
                            <label for="emailaddress" class="sr-only">Email address</label>
                            <input placeholder="Email" type="email" data-validate="{required:true, 'validate-email':true}" data-msg-required="Please enter a valid email address." id="emailaddress" name="emailaddress">
                        </div>
                    </div>
                    <div class="field-wrapper">
                        <div class="form-group">
                            <label for="mobilenumber" class="sr-only">Mobile number</label>
                            <input placeholder="Mobile Number" type="text" data-validate="{required:true}" data-msg-required="Please enter a valid phone number." data-msg-pattern="Please enter a valid phone number. For example 01 2345 6789 or 1234 457 890." id="mobilenumber" name="mobilenumber"><!--validate-length maximum-length-20 -->
                        </div>
                    </div>
                </div>
                <div class="enquiry-form-row">
                    <div class="field-wrapper">
                        <div class="form-group">
                            <label for="message" class="sr-only">Message</label>
                            <textarea placeholder="Message" id="message" name="message" data-validate="{required:true}" data-msg-required="Please enter a valid Message." rows="3"></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <div class="actions">
                <!--<input name="form_key" type="hidden" value="<?php //echo $block->getFormKey();?>" />-->
                <button class="btn btn-secondary btn-block" type="submit">Submit enquiry</button>
                <button class="btn btn-link btn-block" id="cancel-enquiry">Cancel</button>
            </div>
        </form>

    <?php else: ?>
        <div class="enquiry-form">
            <div class="row-group">
                
                    <div class="actions">
                        
                        <a href="<?php echo $block->getLoginUrl()?>" class="btn btn-secondary btn-block">
                            <?php echo __("Login to Make an enquiry") ?>
                        </a>
                        
                        <button class="btn btn-link btn-block" id="cancel-enquiry">
                            <?php echo __("Cancel") ?>
                        </button>
                    </div>
                
            </div>
        </div>
    <?php endif; ?>
<?php } else { ?>
    <div class="enquiry-form">
        <div class="row-group">
            
                <div class="actions">
                    <div class="form-group text-center">
                        <?php echo __("Vendor does not accept enquiries") ?>
                    </div>
                    <button class="btn btn-secondary btn-block" id="cancel-enquiry">
                        <?php echo __("Cancel") ?>
                    </button>
                </div>
            
        </div>
    </div>
<?php } ?>


