<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Gender $block */
?>
<div class="field gender<?= $block->isRequired() ? ' required' : '' ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('business_type')) ?>"><span><?= $block->escapeHtml(__('Business Type')) ?></span></label>
    <div class="control">
        <select id="<?= $block->escapeHtmlAttr($block->getFieldId('business_type')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('business_type')) ?>" title="<?= $block->escapeHtmlAttr(__('Business Type')) ?>"<?php if ($block->isRequired()) : ?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
            <?php $options = $block->getOptions(); ?>
            <?php $value = $block->getBusinessType(); ?>
            <?php foreach ($options as $option) : ?>
                <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $value) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>
