<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Gender $block */
?>
<div class="field gender<?= $block->isRequired() ? ' required' : '' ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('country_code')) ?>"><span><?= $block->escapeHtml(__('Country/Region Code')) ?></span></label>
    <div class="control">
        <select id="<?= $block->escapeHtmlAttr($block->getFieldId('country_code')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('country_code')) ?>" title="<?= $block->escapeHtmlAttr(__('Country/Region Code')) ?>"<?php if ($block->isRequired()) : ?> class="validate-select"<?php endif; ?>>
            <?php $options = $block->getOptions(); ?>
            <?php $value = $block->getCountryCode(); ?>
            <?php foreach ($options as $option) : ?>
                <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?= ($option->getValue() == $value) ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>
