<?php
/**
 * @var $block \Magento\Backend\Block\Template
 */
?>
<script>
    require([
        "prototype"
    ], function () {
        window.locationUrl = '<?= /** @noEscape */ $block->getUrl('omnyfy_vendorfeatured/sources/index')?>';
        window.tagUrl = '<?= /** @noEscape */ $block->getUrl('omnyfy_vendorfeatured/sources/index')?>';
        window.vendorFeaturedId = '<?= /** @noEscape */ $block->getRequest()->getParam('vendor_featured_id') ?>';
    });
</script>
