<?php
$policyTitle = __('Privacy Policy');
?>
<div class="private-policy">
    <span><?= __('Read our %1 here.', '<a href="/privacy-policy">' . $policyTitle . '</a>') ?></span>
</div>
<div class="customer-request">
    <h1 class="page-title">
        <span><?= __('Customer data request') ?></span>
    </h1>
    <div class="request-content">
        <p>Depending on where you are a resident, you may have rights in relation to the information we hold about you.</p>
        <p>If you would like to make a request to access your data or to delete your account, please click on the below link
            to email us,
            and specify your request in the email subject line. We will strive to process your request as swiftly as
            possible.</p>
    </div>
    <a class="button action primary" href="mailto:cs@vermillionlifestyle.com"
       target="_blank"><?= __('Contact Us') ?></a>
</div>