<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Shipping\Block\Adminhtml\View\Form $block
 */
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
$order = $block->getShipment()->getOrder();
$orderId = $order->getId();
$shipBlock = $block->getLayout()->createBlock('Omnyfy\Easyship\Block\Adminhtml\Order\ShipmentCreate');

$sourceStockId = $block->getShipment()->getSourceStockId();
$sourceCode = $block->getShipment()->getSourceCode();
$vendorHelper =  $this->helper('Omnyfy\Vendor\Helper\Data');
$source = $vendorHelper->getSourceBySourceCode($sourceCode);
$sourceStockId = $vendorHelper->getSourceStockIdBySourceCode($sourceCode);
$shippingInfo = $vendorHelper->getQuoteShippingInfo($order->getQuoteId());


$vendorId = null;
if (!empty($source)) {
    $vendorId = $source->getVendorId();
}

$method = $shipBlock->getQuoteShipping($order->getQuoteId(), $sourceCode, $sourceStockId);
$isEasyshipMethod = strpos($method['method_code'], 'easyship_easyship');
$selected = $shipBlock->getSelectedCourier($orderId, $sourceStockId);
$courierId = null;
$courierEntityId = null;
if ($selected != null && $selected->getCourierId()) {
    $courierId = $selected->getCourierId();
    $courierEntityId = $selected->getEntityId();
}
$shipmentDetail = $shipBlock->getEasyshipShipmentDetail($orderId, $sourceStockId);
$easyShipmentId = null;
if ($shipmentDetail != null) {
    $easyShipmentId = $shipmentDetail->getEasyshipShipmentId();
}

$urlBookShip = $block->getUrl("omnyfy_easyship/shipment/ajaxCreateShipmentBuyLabel");
$urlGenerateLabel = $block->getUrl("omnyfy_easyship/shipment/ajaxRegenerateLabel");
$urlCancelShipment = $block->getUrl("omnyfy_easyship/shipment/ajaxCancelShipment");
$canCancelShipment = $shipBlock->canCancelShipment($orderId,$sourceStockId,$courierEntityId);
?>
<?= $block->getChildHtml('order_info'); ?>
<section class="admin__page-section order-shipment-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Method')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Payment Information')); ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div><?= $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?= $block->escapeHtml(__('The order was placed using %1.', $order->getOrderCurrencyCode())); ?>
                </div>
            </div>
        </div>

        <div class="admin__page-section-item order-shipping-address">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Shipping and Tracking Information')); ?></span>
            </div>

            <?php if ($shipBlock->isEasyshipEnabled() && $isEasyshipMethod !== false): ?>
                <div class="admin__page-section-item-content">
                    <div class="shipping-description-wrapper">
                        <table class="data-table admin__table-secondary order-subtotal-table">
                            <tr>
                                <td><b>Customer Selection Option</b></td>
                                <td>
                                    <b><?php echo $block->escapeHtml($method['carrier'].' - '.$method['method_title']) ?>:</b>
                                    <?php echo $shipBlock->addCurrencyToAmount($method['amount']) ?>
                                </td>
                            </tr>
                            <?php if($selected != null && $method['carrier'] != $selected->getCourierName()): ?>
                                <tr>
                                    <td><b>Vendor Booked Option</b></td>
                                    <td>
                                        <b><?php echo $block->escapeHtml($selected->getCourierName()) ?>:</b>
                                        <?php echo $shipBlock->addCurrencyToAmount($selected->getTotalCharge()) ?>
                                    </td>
                                </tr>
                            <?php endif; ?>
                        </table>
                    </div>
                </div>
                <br/>
                <?php if ($shipBlock->getLabelUrl($orderId, $sourceStockId) != null): ?>
                    <a href="<?= $shipBlock->getLabelUrl($orderId, $sourceStockId); ?>" target="_blank" rel="noopener noreferrer" class="action-default">Download and Print Label</a>
                    <a href="<?= $block->getUrl('omnyfy_easyship/bookpickup/index');?>" class="action-default">Go to Pickup Management</a>
                    <?php if($canCancelShipment){ ?>
                        <button class="action-default" id="cancelshipment">Cancel Shipment</button>
                    <?php } ?>
                    <p>Print and attach the labels for this shipment. Once you are ready to ship you can Book Pickup of the items with the courier company.</p>
                <?php elseif ($shipmentDetail && $shipmentDetail->getStatus() != 'cancelled'): ?>
                    <a href="#" class="action-default" id="generatelabel">Generate Label</a>
                <?php else: ?>
                    <?php if ($courierId != null): ?>
                        <a href="#" class="action-default" id="bookshipment">Book Shipment and Get Label</a>
                    <?php endif; ?>
                <?php endif; ?>

            <?php else:?>
                <div class="admin__page-section-item-content">
                    <div class="shipping-description-wrapper">
                        <?php if ($block->getShipment()->getTracksCollection()->count()) : ?>
                            <p>
                                <a href="#" id="linkId" onclick="popWin('<?= $block->escapeUrl($this->helper(\Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($block->getShipment())); ?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')"
                                title="<?= $block->escapeHtml(__('Track this shipment')); ?>">
                                    <?= $block->escapeHtml(__('Track this shipment')); ?>
                                </a>
                            </p>
                        <?php endif; ?>
                        <table>
                            <?php foreach ($shippingInfo as $shipping): ?>
                                <?php if ($shipping['vendor_id'] == $vendorId) : ?>
                                    <tr>
                                        <td><b><?= $shipping['carrier'].' - '.$shipping['method_title'] ?></b></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td><?= __('Total Shipping Charges: ') ?></td>
                                        <td style="padding-left: 5px">
                                           <b><?= $shipBlock->getFormatPrice($shipping['amount'])  ?></b>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </table>

                    </div>

                    <p>
                        <?php if ($block->canCreateShippingLabel()) : ?>
                            <?= /* @noEscape */ $block->getCreateLabelButton(); ?>
                        <?php endif ?>
                        <?php if ($block->getShipment()->getShippingLabel()) : ?>
                            <?= /* @noEscape */ $block->getPrintLabelButton(); ?>
                        <?php endif ?>
                        <?php if ($block->getShipment()->getPackages()) : ?>
                            <?= /* @noEscape */ $block->getShowPackagesButton(); ?>
                        <?php endif ?>
                    </p>
                    <?= $block->getChildHtml('shipment_tracking'); ?>

                    <?= $block->getChildHtml('shipment_packaging'); ?>
                    <script>
                        require([
                            'jquery',
                            'prototype'
                        ], function (jQuery) {
                            var setCallbacks = function () {
                                window.packaging.setConfirmPackagingCallback(function () {
                                    window.packaging.sendCreateLabelRequest();
                                });
                                window.packaging.setLabelCreatedCallback(function () {
                                    setLocation("<?php $block->escapeUrl($block->getUrl('adminhtml/order_shipment/view', ['shipment_id' => $block->getShipment()->getId()])); ?>");
                                });
                            };

                            if (jQuery(document).data('packagingInited')) {
                                setCallbacks();
                            } else {
                                jQuery(document).on('packaging:inited', setCallbacks);
                            }
                        });
                    </script>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Shipped')); ?></span>
    </div>
    <?= $block->getChildHtml('shipment_items'); ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Total')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <?= $block->getChildHtml('shipment_packed'); ?>

        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Shipment History')); ?></span>
            </div>
            <div class="admin__page-section-item-content"><?= $block->getChildHtml('order_comments'); ?></div>
        </div>
    </div>
</section>

<script>
require([
    "jquery",
], function(jQuery){
    jQuery(document).ready(function() {
        jQuery('#bookshipment').click(function(e){
            e.preventDefault();

            jQuery.ajax({
                method: "POST",
                url: "<?= $urlBookShip; ?>",
                dataType: "json",
                data: {
                    form_key: window.FORM_KEY,
                    order_id: <?= $orderId ?>,
                    vendor_id: <?= $vendorId ?>,
                    source_stock_id: <?= $sourceStockId ?>,
                    source_code: "<?= $sourceCode ?>",
                    courier_id: "<?= $courierId ?>",
                    courier_entity_id: "<?= $courierEntityId ?>",
                },
                showLoader:true,
                success: function(response){
                    location.reload();
                },
                error: function () {
                    alert('Something went wrong. Please try again.');
                }
            });
        });

        jQuery('#generatelabel').click(function(e){
            e.preventDefault();
            var easy_shipment_id = "<?= $easyShipmentId ?>";
            if (easy_shipment_id) {
                jQuery.ajax({
                    method: "POST",
                    url: "<?= $urlGenerateLabel; ?>",
                    dataType: "json",
                    data: {
                        form_key: window.FORM_KEY,
                        source_stock_id: <?= $sourceStockId ?>,
                        source_code: "<?= $sourceCode ?>",
                        courier_id: "<?= $courierId ?>",
                        easyship_shipment_id: easy_shipment_id,
                    },
                    showLoader:true,
                    success: function(response){
                        if (response.error && response.message) {
                            alert(response.message);
                        }else{
                            location.reload();
                        }
                    },
                    error: function () {
                        alert('Something went wrong. Please try again.');
                    }
                });
            }else{
                alert('Shipment hasn\'t been created.');
            }
        });

        jQuery('#cancelshipment').click(function(e){
            e.preventDefault();
            var easy_shipment_id = "<?= $easyShipmentId ?>";
            if (easy_shipment_id) {
                jQuery.ajax({
                    method: "POST",
                    url: "<?= $urlCancelShipment; ?>",
                    dataType: "json",
                    data: {
                        form_key: window.FORM_KEY,
                        source_stock_id: <?= $sourceStockId ?>,
                        source_code: "<?= $sourceCode ?>",
                        easyship_shipment_id: easy_shipment_id,
                    },
                    showLoader:true,
                    success: function(response){
                        // console.log(response);
                        location.reload();
                    },
                    error: function () {
                        alert('Something went wrong. Please try again.');
                    }
                });
            }else{
                alert('Shipment hasn\'t been created.');
            }
        });
    });
});
</script>
