<?php
/** @var $block \Omnyfy\Enquiry\Block\Catalog\Vendor */
$_product = $block->getProduct();
if (empty($_product)) return;

$locationUrl = $block->getLocationUrl();
$vendorId = $block->getVendorId($block->getProductId());
?>
<div id="vendor-actions" data-bind="scope:'vendorActions'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
       {
           "#vendor-actions": {
              "Magento_Ui/js/core/app": {
                    "components": {
                        "vendorActions": {
                            "component": "Omnyfy_Enquiry/js/vendor-action",
                            "urlLogin": "<?= $block->getLoginUrl() ?>",
                            "formAction": "<?= $block->getFormAction() ?>",
                            "isShowPopup": "<?= $this->getRequest()->getParam('enquiry') == 'yes' ?>",
                            "vendorId": "<?= $vendorId ?>",
                            "productId": "<?= $block->getProductId() ?>"
                        }
                    }
                }
           }
       }
   </script>
</div>
