<?php
$dimensionsParams = $block->getDimensionParam();
?>
<div data-role="collapsible" class="filter-options-item allow">
    <div data-role="title" class="filter-options-title">
        <?= __('Dimensions') ?>
    </div>
    <div data-role="content" class="filter-options-content">
        <div class="filter-items-dimensions"
             data-am-js="fromto-widget">
            <span><?= __('Height %1', '(cm)') ?></span>
            <div class="form-filter dimensions" data-rate="1">
                <input class="input-text" type="number" placeholder="From" name="height_from"
                       value="<?= isset($dimensionsParams['height_from']) ? $dimensionsParams['height_from'] : '' ?>">
                <span class="delimiter"> - </span>
                <input class="input-text" type="number" placeholder="To" name="height_to"
                       value="<?= isset($dimensionsParams['height_to']) ? $dimensionsParams['height_to'] : '' ?>">
            </div>
        </div>

        <div class="filter-items-dimensions" data-am-js="fromto-widget">
            <span><?= __('Width %1', '(cm)') ?></span>
            <div class="form-filter dimensions" data-rate="1">
                <input class="input-text" type="number" placeholder="From" name="width_from"
                       value="<?= isset($dimensionsParams['width_from']) ? $dimensionsParams['width_from'] : '' ?>">
                <span class="delimiter"> - </span>
                <input class="input-text" type="number" placeholder="To" name="width_to"
                       value="<?= isset($dimensionsParams['width_to']) ? $dimensionsParams['width_to'] : '' ?>">
            </div>
        </div>
        <div class="filter-items-dimensions" data-am-js="fromto-widget">
            <span><?= __('Length %1', '(cm)') ?></span>
            <div class="form-filter dimensions" data-rate="1">
                <input class="input-text" type="number" placeholder="From" name="length_from"
                       value="<?= isset($dimensionsParams['length_from']) ? $dimensionsParams['length_from'] : '' ?>">
                <span class="delimiter"> - </span>
                <input class="input-text" type="number" placeholder="To" name="length_to"
                       value="<?= isset($dimensionsParams['length_to']) ? $dimensionsParams['length_to'] : '' ?>">
            </div>

        </div>
        <button class="am-filter-go" id="dimensions-search" title="Search >>">Search >></button>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $('#dimensions-search').on('click', function () {
            var heightFrom = $('input[name=height_from]').val(),
                heightTo = $('input[name=height_to]').val(),
                widthFrom = $('input[name=width_from]').val(),
                widthTo = $('input[name=width_to]').val(),
                lengthFrom = $('input[name=length_from]').val(),
                lengthTo = $('input[name=length_to]').val(),
                urlParams = new URLSearchParams(window.location.search);
            if (heightTo) {
                urlParams.set('height', getDimensionParam(heightFrom, heightTo));
            }
            if (widthTo) {
                urlParams.set('width', getDimensionParam(widthFrom, widthTo));
            }
            if (lengthTo) {
                urlParams.set('length', getDimensionParam(lengthFrom, lengthTo));
            }
            window.location.search = urlParams;
        })

        function getDimensionParam(from, to) {
            from = from ? from : 0;
            return from + '-' + to;
        }
    });
</script>
