<?php
$order = $block->getOrder();
$vendor = $block->getVendor();
/** @var \OmnyfyCustomzation\VendorConfirm\Helper\Data $helper */
$helper = $block->getHelper();
?>

<table class="email-items">
    <thead>
    <tr>
        <th class="item-thumbnail">
            <?= $block->escapeHtml(__('Item')) ?>
        </th>
        <th class="item-info">
            <?= $block->escapeHtml(__('Description')) ?>
        </th>
        <th class="item-qty">
            <?= $block->escapeHtml(__('Qty')) ?>
        </th>
        <th class="item-weight">
            <?= $block->escapeHtml(__('Weight')) ?>
        </th>
        <th class="item-dimensions">
            <?= $block->escapeHtml(__('Dimensions')) ?>
        </th>
        <th class="item-hs-code">
            <?= $block->escapeHtml(__('HS Code')) ?>
        </th>
        <th class="item-price">
            <?= $block->escapeHtml(__('Price')) ?>
        </th>
    </tr>
    </thead>
    <?php foreach ($order->getItems() as $_item) : ?>
        <?php if ($_item->getVendorId() == $vendor->getId()): ?>
            <?php
            $product = $helper->getProductById($_item->getProductId());
            $leadTime = $product->getResource()->getAttribute('lead_time')->getFrontend()->getValue($product);
            $largeOrder = $product->getResource()->getAttribute('large_order_lead_time')->getFrontend()->getValue($product)
            ?>

            <tbody>
            <tr>
                <td class="col-thumbnail">
                    <img src="<?= $helper->getThumbnailItem($product) ?>"
                         alt="<?= $product->getName() ?>"
                         width="100"/>
                </td>
                <td class="item-info">
                    <p class="product-name">
                        <a href="<?= $block->escapeHtml($product->getProductUrl()) ?>" target="_blank">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </p>
                    <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>
                        : <?= $block->escapeHtml($_item->getSku()) ?>
                    </p>
                    <?php if ($leadTime): ?>
                        <p class="lead-time">
                            <b><?= __('MOQ Lead Time: ') ?></b>
                        </p>
                        <p><?= __($leadTime) ?></p>
                    <?php endif; ?>
                    <?php if ($largeOrder): ?>
                        <p class="lead-time">
                            <b><?= __('Large Order Lead Time: ') ?></b>
                        </p>
                        <p><?= __($largeOrder) ?></p>
                    <?php endif; ?>
                </td>
                <td class="item-qty"><?= (int)$_item->getQtyOrdered() ?></td>
                <td class="col-weight">
                    <?php if ($product->getWeight()): ?>
                        <p><?= floatval($product->getWeight()) . ' kgs' ?></p>
                    <?php endif; ?>
                </td>
                <td class="col-dimensions">
                    <?php if ($product->getSwDimensions()): ?>
                        <p><?= $product->getSwDimensions() ?></p>
                    <?php endif; ?>
                </td>
                <td class="col-hs-code">
                    <?php if ($product->getHsCode()): ?>
                        <p><?= $product->getHsCode() ?></p>
                    <?php endif; ?>
                </td>
                <td class="item-price">
                    <?= /* @noEscape */
                    $helper->getFormattedPrice($_item->getPrice()) ?>
                </td>
            </tr>
            </tbody>
        <?php endif; ?>
    <?php endforeach; ?>
</table>