<div class="mst-debugContainer">
    <?php
    /** @var \Mirasvit\Search\Block\Debug $block */
    $results = [];
    $nestedResults = [];
    foreach ($block->getPreparedLogs() as $indexIdentifier => $indexData): ?>
        <span class="mst-identifierToggler">
        Index Identifier : <?= $indexIdentifier ?>
    </span>
        <div class="mst-debugDataHolder">
            <table>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                <?php foreach ($indexData as $key => $log ): ?>
                    <tr>
                        <td><?= $key ?></td>
                        <td><pre class="mst-json_output"><?= json_encode(json_decode($log), JSON_PRETTY_PRINT) ?></pre></td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    <?php endforeach; ?>

    <style type="text/css">
        .mst-debugContainer {
            display:block;
            background: #f9faff;
        }

        .mst-debugDataHolder {
            display:block;
            border-top:1px solid #2a46a8;
            background: #f9faff;
        }

        .mst-identifierToggler{
            display:block;
            padding:10px;
            cursor:pointer;
            border-bottom:1px solid #2a46a8;
            font-size:17px;
            font-weight: 600;
            background: #0f339e;
            color: #fff;
        }
        pre.mst-json_output {
            font-size: 10px;
            white-space: pre-wrap;
        }

    </style>
