<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block Magento\Catalog\Block\Product\View */
?>
<?php
$product = $block->getProduct();
$buttonTitle = __('Add to Cart');

/** @var Smartwave\Dailydeals\Helper\Data $dailyDealHelper */
$dailyDealHelper = $this->helper('Smartwave\Dailydeals\Helper\Data');

/** @var OmnyfyCustomzation\PriceToQuote\Helper\Data $priceQuoteHelper */
$priceQuoteHelper = $this->helper('OmnyfyCustomzation\PriceToQuote\Helper\Data');

?>
<?php if ($product->isSaleable()): ?>
    <?php if ($priceQuoteHelper->isPriceToQuote($product)): ?>
        <?php echo $priceQuoteHelper->getEmailUsBox($product->getId()) ?>
    <?php else: ?>
        <div class="box-tocart">
            <?php if ($block->getRequest()->getParam('dailydealproduct') || $dailyDealHelper->isDealProduct($product->getId())) : ?>
                <?php $productSku = $product->getSku(); ?>
                <input type="text" id="todate" value="<?php echo $dailyDealHelper->getDailydealToDate($productSku); ?>"
                       style="display:none;">
                <input type="text" style="display: none;" id="fromdate"
                       value="<?php echo $dailyDealHelper->getDailydealFromDate($productSku); ?>">
                <p id="countdown"></p>
                <div class="sw-dailydeal-wrapper">
                    <div class="sw-dailydeal">
                        <?php if ($block->getRequest()->getParam('dailydealproduct')) : ?>
                            <p id="expired"></p>
                        <?php endif; ?>
                        <div class="countdowncontainer" style="display:none;">
            <span class="dailydeal-label">
                <?php echo __('Offer Ends In:'); ?>
            </span>

                            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number day">
                    <p id="countdown_days"></p>
                </span>
                <div class="caption"><?php echo __('Days'); ?></div>
            </span>

                            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number hour"><p id="countdown_hours"></p></span>
                <div class="caption"><?php echo __('Hours'); ?></div>
            </span>

                            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number min"><p id="countdown_minutes"></p></span>
                <div class="caption"><?php echo __('Minutes'); ?></div>
            </span>

                            <span class="number-wrapper">
                <div class="line"></div>
                <span class="number sec"><p id="countdown_seconds"></p></span>
                <div class="caption"><?php echo __('Seconds'); ?></div>
            </span>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                echo __('Qty') ?>:</span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */
                                   echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */
                                   echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                            <div class="qty-changer">
                                <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
                                <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */
                            echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }




    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));
                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        var app = {
            isAppleDevice: function () {
                if (navigator.userAgent.match(/(iPhone|iPod|iPad|Safari)/) != null) {
                    return true;
                }
                return false;
            }
        }
        // Timer for LEFT time for Dailydeal product
        var _second = 1000,
            _minute = _second * 60,
            _hour = _minute * 60,
            _day = _hour * 24,
            timer;

        function showRemaining(currentDate) {
            var startDateId = 'fromdate',
                id = 'todate',
                daysId = 'countdown_days',
                hoursId = 'countdown_hours',
                minutesId = 'countdown_minutes',
                secondsId = 'countdown_seconds',
                endDate = new Date($('#' + id).val()),
                dealstartdate = new Date($('#' + startDateId).val());

            if (app.isAppleDevice() && $('#' + id).val() && $('#' + startDateId).val()) {
                var edate = $('#' + id).val(),
                    edateParts = edate.substring(0, 10).split('-'),
                    etimePart = edate.substr(11);

                endDate = edateParts[1] + '/' + edateParts[2] + '/' + edateParts[0] + ' ' + etimePart;
                endDate = new Date(endDate).getTime();

                var sDate = $('#' + startDateId).val(),
                    sDateParts = sDate.substring(0, 10).split('-'),
                    sTimePart = sDate.substr(11);

                dealstartdate = sDateParts[1] + '/' + sDateParts[2] + '/' + sDateParts[0] + ' ' + sTimePart;
                dealstartdate = new Date(dealstartdate).getTime();
            }
            // Get Current Date from magentodatetime

            var currentDate = new Date(currentDate).getTime(),
                //Get Difference between Two dates
                distance = endDate - currentDate;

            if (distance < 0) {
                $('#expired').html("<div class='offermessage' >EXPIRED!</div>");
            } else if (dealstartdate > currentDate) {
                $('.countdowncontainer').hide();
                var msg = "<div class='offermessage' > Coming Soon..<br>Deal Start at:<br>" + $('#' + startDateId).val() + "</div>";
                $('#expired').html(msg);
            } else {
                var days = Math.floor(distance / _day),
                    hours = Math.floor((distance % _day) / _hour),
                    minutes = Math.floor((distance % _hour) / _minute),
                    seconds = Math.floor((distance % _minute) / _second);

                if (hours < 10)
                    hours = "0" + hours;
                if (minutes < 10)
                    minutes = "0" + minutes;
                if (seconds < 10)
                    seconds = "0" + seconds;
                $('.countdowncontainer').show();
                $('#' + daysId).html(days);
                $('#' + hoursId).html(hours);
                $('#' + minutesId).html(minutes);
                $('#' + secondsId).html(seconds);
            }
        }

        //Set date as magentodatetime
        var date = new Date('<?php echo $dailyDealHelper->getcurrentDate() ?>');
        if (app.isAppleDevice()) {
            var mdate = '<?php echo $dailyDealHelper->getcurrentDate() ?>',
                dateParts = mdate.substring(0, 10).split('-'),
                timePart = mdate.substr(11);

            date = dateParts[1] + '/' + dateParts[2] + '/' + dateParts[0] + ' ' + timePart;
            date = new Date(date);
        }
        var day = date.getDate(),
            month = date.getMonth(),
            year = date.getFullYear(),
            hours = date.getHours(),
            minutes = "0" + date.getMinutes(),
            seconds = "0" + date.getSeconds(),
            // Set Interval
            timer = setInterval(function () {
                date.setSeconds(date.getSeconds() + 1);
                var month = date.getMonth(),
                    currentDatetime = date.getFullYear() + "/" + (month + 1) + "/" + date.getDate() + " " + date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
                showRemaining(currentDatetime);
            }, 1000);
    });
</script>