<div class="admin__field" style="display: inline-block;width: 100%;margin-top: -20px;margin-bottom: 20px;">
    <div class="admin__field-control" style="width: calc( (100%) * 0.5 - 30px );float: left;margin-left: calc( (100%) * 0.25 + 10px );">
        <div class="field-tooltip-content">
            <span>
                <?= $block->getCommentText(); ?>
            </span>
        </div>
    </div>
</div>