<div style="display:none">
<?php $product_id = $block->getProductId()?>
<?php $vendor_id = $block->getVendorId($product_id)?>
<?php $customer_id = $block->getCustomerId() ?>
<?php $store_id = $block->getStoreId() ?>
</div>

<?php if($block->isEnable($vendor_id, $product_id)): ?>
<div class="enquiry-form">
    <form class="form contact-omnyfy" action="" id="enquiry-form1" method="post" novalidate="novalidate">
        <div class="form-head">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title">Make an enquiry</h4>
        </div>
        <div class="form-body">
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="hidden" name="vendor_id" value="<?php echo $vendor_id ?>">
            <input type="hidden" name="product_id" value="<?php echo $product_id ?>">
            <input type="hidden" name="customer_id" value="<?php echo $customer_id ?>">
            <input type="hidden" name="store_id" value="<?php echo $store_id ?>">

            <div class="form-group">
                <label for="firstname">First Name <span class="red">*</span></label>
                <input type="text" class="form-control validate-alpha" id="firstname" name="firstname" >
            </div>
            <div class="form-group">
                <label for="lastname">Last Name <span class="red">*</span></label>
                <input type="text"  class="form-control validate-alpha" id="lastname" name="lastname" >
            </div>
            <div class="form-group">
                <label for="emailaddress">Email address <span class="red">*</span></label>
                <input type="email"  class="form-control validate-alpha" id="emailaddress" name="email" >
            </div>
            <div class="form-group">
                <label for="mobilenumber">Mobile number <span class="red">*</span></label>
                <input type="text"  class="form-control validate-alpha" id="mobilenumber" name="mobile" >
            </div>
            <div class="form-group">
                <label for="company">Company <span class="red">*</span></label>
                <input type="text"  class="form-control validate-alpha" id="company"  name="company" >
            </div>
            <div class="form-group">
                <label for="message">Message <span class="red">*</span></label>
                <textarea id="message" class="form-control validate-alpha" name="message" rows="3" ></textarea>
            </div>
            <div class="form-group">
                <i>All the fields are required.</i>
            </div>
            <div class="form-group">
                <div id="message-complete" class="message-complete" style="display:none"></div>
            </div>
        </div>
        <div class="form-footer">
            <button id="submit-enquiry" name="submit-enquiry" class="btn">Submit enquiry</button>
        </div>
    </form>
</div>
<div class="mobile-only enq-cta">
    <button id="enq-mobile-btn">
        Make an enquiry
    </button>
</div>
<script>
    require(
        ["jquery"],
        function($) {
            $(document).ready(function () {
                $('#submit-enquiry').click(function (e) {
                    e.preventDefault();

                    var firstName = $("input[name='firstname']").val();
                    var lastName = $("input[name='lastname']").val();
                    var email = $("input[name='email']").val();
                    var mobile = $("input[name='mobile']").val();
                    var company = $("input[name='company']").val();
                    var message = $("textarea[name='message']").val();
                    var vendorId = $("input[name='vendor_id']").val();
                    var productId = $("input[name='product_id']").val();
                    var customerId = $("input[name='customer_id']").val();
                    var storeId = $("input[name='store_id']").val();

                    if (firstName == "" || lastName == "" || email == "" || mobile == "" || company == "" || message == "")
                    {
                        $("#message-complete").show();
                        $("#message-complete").addClass("error")
                        $("#message-complete").html("Please fill all the required fields.");
                        $("#message-complete").delay(5000).fadeOut("slow");
                        return false;
                    }

                    var url = "<?php echo $block->getFormSubmitUrl() ?>";
                    jQuery.ajax({
                        url: url,
                        type: "POST",
                        data: {
                            firstName: firstName,
                            lastName: lastName,
                            email: email,
                            mobile: mobile,
                            company: company,
                            message: message,
                            vendorId:vendorId,
                            productId:productId,
                            customerId:customerId,
                            storeId:storeId
                        },
                        showLoader: true,
                        cache: false,
                        success: function (response) {
                            $("#message-complete").show();
                            $("#message-complete").html("Successfully sent the enquiry");
                        }
                    });
                    $("#message-complete").delay(5000).fadeOut("slow");
                });

                $('#enq-mobile-btn').click(function () {
                    $('input[name=firstname]').focus();
                    $('.enquiry-form').addClass("active");
                });

                $("button.close").click(function () {
                    $('.enquiry-form').removeClass("active");
                });
            });
        }
    );
</script>
<style>
    .sidebar.sidebar-main:before {
        display: none;
    }

    .enquiry-form .form-head {
        margin-bottom: 25px;
    }

    .enquiry-form div#message-complete {
        color: #fff;
        padding: 5px 10px;
        margin-bottom: 10px;
    }

    .enquiry-form div#message-complete.success {
        background-color: #24c91f;
    }

    .enquiry-form div#message-complete.error {
        background-color: #f63e3e;
    }

    .enquiry-form {
        padding: 20px;
    }

    .enquiry-form .form-group {
        margin-bottom: 10px;
    }

    .enquiry-form .form-group label {
        margin-bottom: 5px;
        display: block;
        font-family: 'Letter', Arial, Helvetica, sans-serif;
        font-size: 14px;
        font-weight: 400;
        letter-spacing: 0.005em;
        line-height: 20px;
    }

    .enquiry-form button#submit-enquiry {
        width: 100%;
        background-color: #009987;
        color: #fff;
        border: none;
        text-transform:  UPPERCASE;
        height: 43px;
        font-size: 14px;
        letter-spacing: 0.05em;
        font-weight: 400;
    }

    .enquiry-form span.red {
        color: #f63e3e;
    }

    .mobile-only.enq-cta {
        display:none;
    }

    button#enq-mobile-btn {
        border: 1px solid #009987;
        color: #009987;
        box-shadow: none;
        line-height: 46px;
        width: 100%;
        position: fixed;
        bottom: 0;
        background-color: #fff;
        font-size: 17px;
        text-transform: uppercase;
        left: 0;
        right: 0;
        height: auto !important;
    }
    .enquiry-form .close {
        display: none;
    }

    .enquiry-form .close {
        float: right;
        font-size: 21px;
        font-weight: bold;
        line-height: 1;
        color: #000;
        text-shadow: 0 1px 0 #fff;
        filter: alpha(opacity=20);
        opacity: .2;
    }

    .enquiry-form button.close {
        -webkit-appearance: none;
        padding: 0;
        cursor: pointer;
        background: transparent;
        border: 0;
    }

    h4.modal-title {
        text-transform: uppercase;
        font-size: 16px;
    }

    @media (max-width: 991px) {
        .enquiry-form .form-head {
            margin-bottom: 45px;
        }
        .enquiry-form .close,
        .mobile-only.enq-cta {
            display:block;
        }

        .enquiry-form {
            transition: opacity 1s ease-out;
            opacity: 0;
            height: 0;
            overflow: hidden;
        }

        .enquiry-form.active {
            width: 100%;
            position: fixed;
            background: #fff;
            left: 0;
            right: 0;
            bottom: 0;
            z-index: 100;
            opacity: 1;
            height: auto;
            border-top: 1px solid #00000014;
        }

        .catalog-product-view.page-layout-2columns-right:not(.weltpixel-quickview-catalog-product-view) .sidebar {
            display: block;
            width: 100%;
        }
    }

</style>
<?php endif; ?>

