<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var OmnyfyCustomzation\PriceToQuote\Block\Product\Quote $block */
$product = $block->getProduct();
$vendor = $block->getVendor();
$customer = $block->getCurrentCustomer();
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= __('* Required Fields'); ?>">
        <br/>
        <legend class="legend"><span><?= $block->escapeHtml(__('Product Information')) ?></span></legend>
        <br>
        <input type="hidden" name="product_id" value="<?= $product->getId() ?>">
        <?php if ($vendor): ?>
            <div class="field brand_name">
                <label class="label" for="brand_name"><span><?= $block->escapeHtml(__('Brand Name')) ?></span></label>
                <div class="control">
                    <input name="brand_name" id="brand_name" title="<?= $block->escapeHtmlAttr(__('Brand Name')) ?>"
                           value="<?= $vendor->getName() ?>"
                           class="input-text" type="text" readonly="true"/>
                </div>
            </div>
        <?php endif; ?>
        <div class="field product_name">
            <label class="label" for="product_name"><span><?= $block->escapeHtml(__('Product Name')) ?></span></label>
            <div class="control">
                <input name="product_name" id="product_name" title="<?= $block->escapeHtmlAttr(__('Product Name')) ?>"
                       value="<?= $product->getName() ?>"
                       class="input-text" type="text" readonly="true"/>
            </div>
        </div>
        <div class="field product_sku">
            <label class="label" for="brand-name"><span><?= $block->escapeHtml(__('SKU#')) ?></span></label>
            <div class="control">
                <input name="product_sku" id="product_sku" title="<?= $block->escapeHtmlAttr(__('SKU#')) ?>"
                       value="<?= $product->getSku() ?>"
                       class="input-text" type="text" readonly="true"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Your Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Your Name')) ?>"
                       value="<?= $customer ? $customer->getName() : '' ?>"
                       class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       value="<?= $customer ? $customer->getEmail() : '' ?>"
                       class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field inquiry required">
            <label class="label"
                   for="inquiry"><span><?= $block->escapeHtml(__('Inquiry')) ?></span></label>
            <div class="control">
                <textarea name="inquiry" id="inquiry" title="<?= $block->escapeHtmlAttr(__('Inquiry')) ?>"
                          class="input-text" cols="5" rows="3"
                          data-validate="{required:true}"><?= __('Hi! I\'d like to know the price on this item. Could you please send me further information on this piece?') ?></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
