<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\Shipping\Block\Adminhtml\Order\Tracking */
$tracks = $block->getShipment()->getTracks();
?>
<div class="admin__control-table-wrapper">
    <table class="data-table admin__control-table" id="tracking_numbers_table">
        <thead>
        <tr class="headings">
            <th class="col-carrier"><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            <th colspan="2" class="col-title"><?= $block->escapeHtml(__('Tracking Url')) ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($tracks as $track): ?>
            <tr>
                <td class="col-number">
                    <input class="admin__control-text"
                           type="text"
                           name="tracking[1][number]"
                           value="<?= $track->getTrackNumber() ?>"
                           disabled="disabled"/>
                </td>
                <td class="col-title">
                    <input class="admin__control-text"
                           type="text"
                           name="tracking[1][title]"
                           value="<?= $track->getTitle() ?>"
                           disabled="disabled"/>
                </td>
                <input class="admin__control-text"
                       type="hidden"
                       name="tracking[1][carrier_code]"
                       value="custom"
                       disabled="disabled"/>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
