<?php

/**
 * @var \Omnyfy\VendorSignUp\Block\SignUp\Renderers\Renderer $block
 */

$element = $block->getElement();
?>

<div class="field">
    <label class="label <?= $element->getRequired() == 1 ? 'required' : '' ?>"><?= $element->getLabel() ?></label>
    <div class="control">
        <?php if ($element->getType() == 'text') : ?>
            <?php if ($element->getData('is_datetime')): ?>
                <input type="text" id="<?= $element->getHtmlId() ?>" name="<?= $element->getName() ?>" placeholder="<?= __('Enter your ') . $element->getLabel() ?>" <?= $element->getRequired() == 1 ? ' data-validate="{required:true}" ' : '' ?> class="input-text" />
                <script>
                    require([
                        'jquery',
                        'mage/translate',
                        'mage/calendar'
                    ], function($, $t) {
                        $('#<?= $element->getHtmlId() ?>').datetimepicker({
                            timepiker: true,
                            changeMonth: true,
                            changeYear: true,
                            showButtonPanel: true,
                            currentText: $t('Go Today'),
                            closeText: $t('Close'),
                            buttonText: $t('Select'),
                            showOn: 'button',
                            showWeek: true,
                        });
                    })
                </script>
            <?php elseif ($element->getData('is_date')) : ?>
                <input type="text" id="<?= $element->getHtmlId() ?>" name="<?= $element->getName() ?>" placeholder="<?= __('Enter your ') . $element->getLabel() ?>" <?= $element->getRequired() == 1 ? ' data-validate="{required:true}" ' : '' ?> class="input-text" />
                <script>
                    require([
                        'jquery',
                        'mage/translate',
                        'mage/calendar'
                    ], function($, $t) {
                        $('#<?= $element->getHtmlId() ?>').calendar({
                            changeMonth: true,
                            changeYear: true,
                            showButtonPanel: true,
                            currentText: $t('Go Today'),
                            closeText: $t('Close'),
                            buttonText: $t('Select'),
                            showOn: 'button',
                            showWeek: true,
                        });
                        $('.ui-datepicker-trigger.v-middle span').text('Select');
                    })
                </script>
            <?php else : ?>
                <input type="text" id="<?= $element->getHtmlId() ?>" name="<?= $element->getName() ?>" placeholder="<?= __('Enter your ') . $element->getLabel() ?>" <?= $element->getRequired() == 1 ? ' data-validate="{required:true}" ' : '' ?> class="input-text" />
            <?php endif; ?>
        <?php elseif ($element->getType() == 'textarea') : ?>
            <textarea id="<?= $element->getHtmlId() ?>" name="<?= $element->getName() ?>" class="<?= $element->getClass() ?>" <?= $element->getRequired() == 1 ? ' data-validate="{required:true}" ' : '' ?> rows="<?= $element->getRows() ?>" cols="<?= $element->getCols() ?>"></textarea>
        <?php elseif ($element->getType() == 'select' && $element->getData('ext_type')) : ?>
            <?php if ($element->getData('ext_type') == 'multiple') : ?>
                <div class="multiselect" id="<?= $element->getHtmlId() ?>" multiple="mutiple">
                    <?php foreach ($element->getValues() as $value) : ?>
                        <label> <input type="checkbox" class="checkbox validate-one-required-by-name" value="<?= $value['value'] ?>" name="<?= $element->getName() ?>" data-validate="{required:true, 'validate-one-required-by-name':true}" /><?= $value['label'] ?></label>
                    <?php endforeach; ?>
                </div>
            <?php else : ?>
                <?php
                $dataValues = $element->getValues();
                ?>
                <select id="<?= $element->getHtmlId() ?>" name="<?= $element->getName() ?>" <?= $element->getRequired() == 1 ? ' data-validate="{required:true}" ' : '' ?>>
                    <?php foreach ($element->getValues() as $value) : ?>
                        <?php if ($dataValues[0] !=  $value) : ?>
                            <option value="<?= $value['value'] ?>"><?= $value['label'] ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        <?php elseif ($element->getType() == 'file') : ?>
            <input type="file" id="<?= $element->getHtmlId() ?>" <?= $element->getRequired() == 1 ? ' data-validate="{required:true}" ' : '' ?> class="input-file-<?= $element->getHtmlId() ?>" />
            <input type="hidden" name="<?= $element->getName() ?>" />
            <script>
                require([
                    'jquery',
                    'mage/translate'
                ], function($) {
                    $(".input-file-<?= $element->getHtmlId() ?>").on("change", function() {
                        var file = $(this).get(0).files[0];
                        var formData = new FormData();

                        formData.append('file', file);
                        let ajaxUploadUrl = '<?= $this->getUrl('vendorsignup/upload/uploadDocumentAttribute') ?>' 

                        $.ajax({
                            url: ajaxUploadUrl,
                            cache: false,
                            contentType: false,
                            processData: false,
                            type: 'POST',
                            showLoader: true,
                            data: formData,
                            success: function(response) {
                                $('.file-upload-message-<?= $element->getHtmlId() ?>').remove();
                                $(".input-file-<?= $element->getHtmlId() ?>").after('<i class="file-upload-message-<?= $element->getHtmlId() ?>" style="font-size: 12px">' + response["message"] + '</i>')
                                if (response.type == 'success') {
                                    $("input[name='<?= $element->getName() ?>']").val(response["filelist"]);
                                }
                            },
                            fail: function() {
                                alert('Something went wrong while uploading the file.')
                            },
                            always: function() {}
                        });
                    });
                })
            </script>
        <?php endif; ?>
    </div>
</div>