<?php
/* @var \Omnyfy\VendorSignUp\Block\SignUp\Form $block */
$stripeSubHelper = $this->helper('Omnyfy\StripeApi\Helper\Data');
$stripeApiKey = $stripeSubHelper->getPublicKey();
$countryList=$block->getCountries();
?>
<div id="stripe-api-key-242" style="display:none;"><?=$stripeApiKey?></div>
<div class="vendor-signup-wrapper" id="vendor-signup-wrapper">
    <?php echo $this->getChildHtml('vendor_signup_form_before')?>
    <div class="vendor-signup-form-wrapper">
        <form class="form signup-omnyfy" name="vendor-signup" action="<?php #echo $block->getFormAction()?>" id="vendor-signup-form" method="post" novalidate="novalidate">
            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
            <input type="hidden" name="vendor_type_id" value="<?php echo $block->getVendorTypeId();?>"/>
            <div class="fieldset">
                <div class="field notice"><?= __('Complete the form to sign up')?></div>
                <?php if ($block->displayFormWholeSale()): ?>
                  <div class="field field-payout-basis-type">
                    <label class="label payout-basis-type-label" for="payout_basis_type"><?= $block->getWholeSaleQuestion();?></label>
                    <div class="control">
                        <select id="payout-basis-type" data-validate="{required:true}" class="input-class-check" name="payout_basis_type">
                          <?php $options = $block->getOptionPayoutBasisType();
                           ?>
                            <?php foreach ($options as $option): ?>
                              <option value="<?= $option['value']?>" <?php if ($block->getDefaultVendorPayout() == $option['value']) echo "selected='selected'"?>><?= $option['label']?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="comment">
                      <p><strong><?= __('A Commission Based Vendor') ?></strong><?= __(' will receive a payout based on the selling price of the product, less any applicable discounts and promotions and any commissions charged by the marketplace.') ?></p>
                      <p><strong><?= __('A Wholesale Price Based Vendor') ?></strong><?= __(' will receive payouts based on the provided Wholesale Price. This price will not be affected by the retail price paid by the customer. Note if you select this price, you must provide the Wholesale Price when creating your products.') ?></p>
                </div>
                    </div>
                <?php endif ?>
                <h4><?= __("Your information")?></h4>
                <fieldset class="your-information">
                    <div class="field field-firstname">
                        <label class="label" for="firstname"><?= __('First Name')?></label>
                    <div class="control">
                            <input type="text"
                                   placeholder="<?= __('First Name')?>"
                                   class="input-class-check maximum-length-100"
                                   data-validate="{required:true}"
                                   id="firstname"
                                   name="firstname">
                    </div>
                </div>
                    <div class="field field-lastname">
                        <label class="label" for="lastname"><?= __('Last Name')?></label>
                    <div class="control">
                            <input type="text"
                                   placeholder="<?= __('Last Name')?>"
                                   class="input-class-check maximum-length-100"
                                   data-validate="{required:true}"
                                   id="lastname"
                                   name="lastname">
                    </div>
                </div>
                    <div class="field field-contact-number">
                    <label class="label" for="contactnumber"><?= __('Contact Number')?></label>
                    <div class="control complex-field">
                        <div>
                            <select id="countrycode" data-validate="{required:true}" class="input-class-check" name="countrycode">
                                    <option value=""><?= __('Country Code')?></option>
                                <?php echo $block->countrySelector();?>
                            </select>
                        </div>
                        <div>
                                <input type="text"
                                       data-validate="{required:true}"
                                       class="input-class-check"
                                       data-msg-required="<?= __('Please enter a valid phone number.')?>"
                                       data-msg-pattern="<?= __('Please enter a valid phone number. For example 01 2345 6789 or 1234 457 890.')?>"
                                       placeholder="<?= __('Contact Number')?>"
                                       id="contactnumber"
                                       name="contactnumber">
                        </div>
                    </div>
                </div>
                    <div class="field email field-email">
                    <label class="label" for="email"><?= __('Email')?></label>
                    <div class="control email email-section">
                            <input type="text"
                                   placeholder="<?= __('Enter your email address')?>"
                                   data-validate="{required:true, 'validate-email':true}"
                                   class="input-class-check"
                                   data-msg-required="<?= __('Please enter a correct email address.')?>"
                                   id="email"
                                   name="email">
                        <div for="email" generated="true" class="mage-error" id="email-error"></div>
                        </div>
                    </div>
                </fieldset>

                <h4><?= ("Your Business Information")?></h4>
                <fieldset class="business-information">
                    <div class="field field-store-name">
                        <label class="label" for="businessname"><?= __('Store Name')?></label>
                        <div class="control">
                            <input type="text"
                                   placeholder="<?= __('Store Name')?>"
                                   class="input-class-check maximum-length-100"
                                   data-validate="{required:true}"
                                   id="businessname"
                                   name="businessname">
                    </div>
                </div>
                    <div class="field field-legal-entity">
                    <label class="label" for="legal_entity"><?= __('Legal Entity Name')?></label>
                    <div class="control">
                            <input type="text"
                                   placeholder="<?= __('Legal Entity Name')?>"
                                   class="input-class-check"
                                   data-validate="{required:true}"
                                   id="legal_entity"
                                   name="legal_entity">
                    </div>
                </div>
                    <div class="field field-tax">
                    <label class="label" for="businessapn"><?= __('Tax Number')?></label>
                    <div class="control complex-field">
                        <div id="taxnumber-apl">
                            <select id="tax_number" class="input-class-check" data-validate="{required:true}" name="tax_number">
                                <option value=""><?= __('Tax Name')?></option>
                            </select>
                        </div>
                        <div id="contactnumber-apl">
                                <input type="text"
                                       class="input-class-check"
                                       placeholder="<?= __('Enter your Tax Number')?>"
                                       data-validate="{required:true}"
                                       data-msg-required="<?= __('Enter your tax number. If your tax is ABN please enter a valid number e.g. 53004085616 or whatever the validation rule is.')?>"
                                       id="businessapn"
                                       name="businessapn">
                            <div for="businessapn" generated="true" class="mage-error" style="display:none;" id="businessapn-error"></div>
                        </div>
                    </div>
                </div>
                    <div class="field field-business-description">
                    <label class="label" for="businessdescription"><?= __('Business Description')?></label>
                        <div class="control">
                            <textarea name="businessdescription"
                                      placeholder="<?= __('Business Description')?>"
                                      data-validate="{required:true}"
                                      id="businessdescription"
                                      title="<?= __('What’s on your mind?')?>"
                                      class="maximum-length-100 input-class-check input-text"
                                      cols="5"
                                      rows="8"></textarea>
                        </div>
                    </div>
                </fieldset>

                <h4><?= ("Address")?></h4>
                <fieldset class="business-address">
                    <div class="field field-address">
                        <label class="label" for="businessaddress"><?= __('Business Address')?></label>
                    <div class="control">
                            <input type="text"
                                   data-validate="{required:true}"
                                   class="input-class-check"
                                   placeholder="<?= __('Type in your address')?>"
                                   id="businessaddress"
                                   name="businessaddress">
                        </div>
                    </div>
                    <input id="vendor_latitude" type="hidden" name="latitude">
                    <input id="longitude" type="hidden" name="vendor_longitude">
                    <div class="field field-city">
                        <label class="label" for="city"><?= __('City')?></label>
                        <div class="control">
                            <input type="text"
                                   placeholder="<?= __('City/Suburb')?>"
                                   data-validate="{required:true}"
                                   class="input-class-check"
                                   id="city"
                                   name="city">
                        </div>
                    </div>
                    <div class="field field-state">
                        <label class="label" for="state"><?= __('State')?></label>
                        <div class="control">
                            <input type="text"
                                   placeholder="<?= __('State')?>"
                                   class="input-class-check"
                                   data-validate="{required:true}"
                                   id="state"
                                   name="state">
                        </div>
                    </div>
                    <div class="field field-postcode">
                        <label class="label" for="postcode"><?= __('Postcode')?></label>
                        <div class="control">
                            <input type="text"
                                   placeholder="<?= __('Postcode')?>"
                                   class="input-class-check"
                                   data-validate="{required:true}"
                                   id="postcode"
                                   name="postcode">
                        </div>
                    </div>
                    <div class="field field-country">
                        <label class="label" for="country"><?= __('Country')?></label>
                        <div class="control">
                            <?php echo $countryList?>
                    </div>
                </div>
                </fieldset>

                <!-- load custom vendor attributes -->
                <h4><?= ("Other Information")?></h4>
                <fieldset class="custom-attributes">
                <?php echo $block->getChildHtml('vendor_attributes');?>
                </fieldset>

                <input type="hidden" name="file-name" value="" />
            </div>

            <?php echo $this->getChildHtml('additional.data')?>

            <?php echo $this->getChildHtml('msp-recaptcha')?>

            <p class="step-actions">
            <p>
                <?= sprintf('By continuing to sign up, you are agreeing to the %1$s of %2$s and our %3$s',
                    '<a href="' . $this->getUrl('terms-and-conditions') . '">' . __('Terms and Conditions') . '</a>',
                    $block->getStoreName(),
                    '<a href="' . $this->getUrl('privacy-policy-cookie-restriction-mode') . '">' . __('Privacy Policy.') . '</a>'
                )?>
            </p>
            <div class="actions-toolbar">
                <button id="cancel-signup" class="action secondary"><?= __('Cancel')?></button>
                    <button class="action primary" id="confirm-signup"><?= __('Sign up')?></button>
            </div>
    </div>
    </form>
</div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Omnyfy_VendorSignUp/js/form-submit": {
            "formActionUrl": "<?= $block->getFormAction() ?>",
            "ajaxUploadUrl": "<?= $this->getUrl('vendorsignup/upload/index') ?>",
            "ajaxEmailValidationUrl": "<?= $block->getEmailCheckAction() ?>"
        }
    }
}
</script>
<script type="text/javascript">
    require([
        'jquery',
        'Omnyfy_VendorSignUp/js/input-mask'
    ], function ($) {
        $('#contactnumber').simpleMask({
            'mask': ['###-###-####']
        });
    });
    // ]]>
</script>

