<?php /** @var Omnyfy\VendorSignUp\Block\Adminhtml\TextFieldWithBtn\GetGeoCode $block */?>
<button class="get-geocode-btn">Get Geocode</button>
<script type="text/x-magento-init">
     {
            ".get-geocode-btn": {
                "Omnyfy_VendorSignUp/js/getGeoCode": {
                    "fetchGeoCodeUrl": "<?= $block->fetchGeoCodeUrl()?>",
                    "vendorId": "<?= $block->getVendorId()?>"
                }
            }
        }
</script>