<?php
$helper = $this->helper('Omnyfy\VendorReview\Helper\Data');
?>
<input type="hidden" id="leave-feedback" name="leave-feedback" value="<?= $helper->isDisplayVendorReviewOnOrder() || $helper->isDisplayProductReviewOnOrder(); ?>">
<?php if($helper->isDisplayVendorReviewOnOrder() || $helper->isDisplayProductReviewOnOrder()): ?>
	<input type="hidden" id="leave-feedback-tabs-name" name="leave-feedback-tabs-name" value="<?= $helper->getTitleHeaderTab(); ?>">
<?php endif; ?>

<script type="text/javascript">
	require(["jquery"], function($){
		$( document ).ready(function() {
			if($("#leave-feedback").val() == 0){
				$(".leave-feedback-tabs").remove();
			}
			
		});
	});
</script>