<?php
/* @var $block \Omnyfy\VendorReview\Block\Order\Review */
?>
<?php
$helper = $this->helper('Omnyfy\VendorReview\Helper\Data');
?>
<?php if($helper->isDisplayVendorReviewOnOrder() || $helper->isDisplayProductReviewOnOrder()): ?>
<div class="order-details-items review">
    <?= $block->getChildHtml('review.enhancement.vendor.list') ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                <span><?= $block->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>
<?php endif; ?>
