<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */
$_item = $block->getItem();
$_item->setStoreId($block->getOrder()->getStoreId());
$block->setPriceDataObject($_item);

/** @var \OmnyfyCustomzation\Mcm\Helper\Data $helper */
$helper = $this->helper(\OmnyfyCustomzation\Mcm\Helper\Data::class);
$product = $helper->getProductById($_item->getProductId());
$leadTimeAttr = $product->getResource()->getAttribute('lead_time');
$leadTime = $leadTimeAttr ? $leadTimeAttr->getFrontend()->getValue($product) : null;
?>
<tr>
    <td class="col-thumbnail">
        <img src="<?= $helper->getThumbnailItem($product) ?>" alt="<?= $product->getName() ?>" width="100">
    </td>
    <td><?php echo $block->getColumnHtml($_item, 'vendorname') ?></td>
    <td class="col-product">
        <?php echo $block->getColumnHtml($_item, 'name') ?>
    </td>
    <td class="col-price">
        <p>
            <?= $block->getColumnHtml($_item, 'price') ?>
        </p>
    </td>
    <td class="col-qty"><?php /* @escapeNotVerified */
        echo $_item->getQty() * 1 ?></td>
    <td class="col-subtotal">
        <?php echo $block->getColumnHtml($_item, 'subtotal'); ?>
    </td>
    <td class="col-lead-time">
        <?php if ($leadTime): ?>
            <p class="lead-time"><?= __($leadTime) ?></p>
        <?php endif; ?>
    </td>
    <td class="col-weight">
        <?php if ($product->getWeight()): ?>
            <p><?= floatval($product->getWeight()) . ' kgs' ?></p>
        <?php endif; ?>
    </td>
    <td class="col-dimensions">
        <?php if ($product->getSwDimensions()): ?>
            <p><?= $product->getSwDimensions() ?></p>
        <?php endif; ?>
    </td>
    <td class="col-hs-code">
        <?php if ($product->getHsCode()): ?>
            <p><?= $product->getHsCode() ?></p>
        <?php endif; ?>
    </td>
    <td class="col-tax"><?php /* @escapeNotVerified */
        echo $block->displayPriceAttribute('tax_amount') ?></td>
    <td><?php echo $block->getColumnHtml($_item, 'sellerfees'); ?></td>
    <td><?php echo $block->getColumnHtml($_item, 'categoryfees') . '(' . $block->getColumnHtml($_item, 'categoryrate') . ')'; ?></td>
    <td><?php echo $block->getColumnHtml($_item, 'taxpercentageonfees'); ?></td>
    <td class="col-discount"><?php /* @escapeNotVerified */
        echo $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $block->getColumnHtml($_item, 'total'); ?>
    </td>
</tr>
