<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var OmnyfyCustomzation\B2C\ViewModel\Wishlist\Retail $retailHelper */
$retailHelper = $block->getData('retail'); ?>

<?php if ($retailHelper->isShowRetailPrice($product)): ?>
    <div class="retail-price" id="retail-price" data-bind="scope: 'retail-price-component'">
        <fieldset class="fieldset">
            <?php if ($product->isSaleable()) : ?>
                <div class="">
                    <button type="button" data-post='<?= /* @noEscape */
                    $block->getItemAddToCartParams($item) ?>'
                            title="<?= $block->escapeHtmlAttr(__($retailHelper->getRetailLabel())) ?>"
                            data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>"
                            class="">
                        <span><?= $block->escapeHtml(__($retailHelper->getRetailLabel())) ?></span>
                    </button>
                </div>
            <?php else : ?>
                <?php if ($product->getIsSalable()) : ?>
                    <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                    </p>
                <?php else : ?>
                    <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </p>
                <?php endif; ?>
            <?php endif; ?>
        </fieldset>
    </div>
<?php endif; ?>
