    <?php
    $invoiceData = $block->getData('invoice_data');
    $totalShippingCostCalculated = $block->getData('total_shipping_cost_calculated');
    $logo = $block->getData('logo');
    $storename = $block->getData('storename');
    $feecharge = $block->getData('feecharge');
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $tableData = $objectManager->get('Omnyfy\Mcm\Controller\Adminhtml\PayoutHistory\VendorInvoice');
    $invoiceFrom = $tableData->getInvoiceFrom($invoiceData);

    $totalRebate = 0;
    ?>
    <body class="vendor_invoice" style="font-family: Arial, Helvetica, sans-serif">
    <!--HEADING-->
    <table style="table-layout: fixed; width: 100%;">
        <tr>
            <?php if(!empty($logo)): ?>
                <td style="width:150px;">
                    <img src="<?= $logo ?>" style="max-width: 150px;">
                </td>
            <?php endif; ?>
            <td>
                <h1><?= $tableData->getMoName() ?></h1>
            </td>
            <td></td>
        </tr>
    </table>

    <div style="font-size: 16px; margin-bottom: 30px; font-family: Arial, Helvetica, sans-serif">
        <b style="font-size: 24px"><?= __('Vendor Payout Invoice') ?></b> <br>
    </div>

    <table class="header" cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; font-size: 13px; font-family: Arial, Helvetica, sans-serif">
        <tr>
            <td style="text-align: left;vertical-align: text-top;">
                <b><?= __('Invoice To') ?></b>
                <br/>
                <br/>
                <?= $invoiceData->getVendorName() ?>
                <br/>
                <br/>
                <br/>
                <br/>
                <b><?= __('Tax Invoice') ?></b>
                <br/>
                <br/>
                <?= __('Invoice #: ') . $invoiceData->getIncrementId() ?>
                <br/>
                <br/>
                <?= __('Invoice Date: ') . $tableData->getDateFormat($invoiceData);  ?>
            </td>
            <td style="text-align: right;vertical-align: text-top;">
                <b><?= __('Invoice from') ?></b>
                <br/>
                <br/>
                <?= $tableData->getMoName() ?>
                <br/>
                <br/>
                <?= __('Tax Number: ') .  $invoiceFrom['tax_number']?>
                <br/>
                <br/>
                <?= $invoiceFrom['address_line1'] . ' ' . $invoiceFrom['address_line2'] ?>
                <br/>
                <br/>
                <?= $invoiceFrom['city'] . ' ' . $invoiceFrom['post_code'] . ' ' . $invoiceFrom['region_name'] ?>
                <br/>
                <br/>
                <?= $invoiceFrom['country_name'] ?>
            </td>
        </tr>
    </table>

    <h3><?= __("Invoice Items") ?></h3>
    <table>
        <thead style="background-color: #ebebef;">
        <tr>
            <td style="padding: 10px 20px;"><?= __("Total Seller Fee") ?></td>
            <td style="padding: 10px 20px;"><?= __("Total Category Commission") ?></td>
            <td style="padding: 10px 20px;"><?= __("Total Disbursement Fee") ?></td>
            <td style="padding: 10px 20px;"><?= __("Tax Name") ?></td>
            <td style="padding: 10px 20px;"><?= __("Tax %") ?></td>
            <td style="padding: 10px 20px;"><?= __("Tax On Fees") ?></td>
            <td style="padding: 10px 20px;"><?= __("Total Fees") ?></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td style="padding: 10px 20px;">
                <?= $tableData->currency($invoiceData->getFeesTotalInclTax() - $invoiceData->getCategoryCommission() -  $invoiceData->getDisbursementFee() - $invoiceData->getFeesTotalTax()) ?>
            </td>
            <td style="padding: 10px 20px;"><?= $tableData->currency($invoiceData->getCategoryCommission()) ?></td>
            <td style="padding: 10px 20px;"><?= $tableData->currency($invoiceData->getDisbursementFee()) ?></td>
            <td style="padding: 10px 20px;"><?= $feecharge->getTaxName() ?></td>
            <td style="padding: 10px 20px;"><?= (int)$feecharge->getTaxRate() ?>%</td>
            <td style="padding: 10px 20px;"><?= $tableData->currency($invoiceData->getFeesTotalTax()) ?></td>
            <td style="padding: 10px 20px;"><?= $tableData->currency($invoiceData->getFeesTotalInclTax()) ?></td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="2"></td>
            <td style="background-color: #ebebef;padding: 10px 20px;" colspan="4">
                <?= __("Total Fees Charged (incl Tax):") ?>
            </td>
            <td style="background-color: #ebebef;padding: 10px 20px;"><?= $tableData->currency($invoiceData->getFeesTotalInclTax()) ?></td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="4" style="background-color: #ebebef;padding: 10px 20px;">
                <?= __("Tax included in Fees (%1 %2%):",$feecharge->getTaxName(),(int)$feecharge->getTaxRate()) ?>
            </td>
            <td style="background-color: #ebebef;padding: 10px 20px;"><?= $tableData->currency($invoiceData->getFeesTotalTax()) ?></td>
        </tr>
        </tfoot>
    </table>

    <p><?= __("%1 has deducted the total amount of %2 which includes Tax %3 %4% amounting to %5 from the orders that have been placed on %6. A statement of orders placed is included belowfor your reference.", $tableData->getMoName(),$tableData->currency($invoiceData->getFeesTotalInclTax()), $feecharge->getTaxName(),(int)$feecharge->getTaxRate(), $tableData->currency($invoiceData->getFeesTotalTax()), $tableData->getMoName() ) ?></p>

    <h3 style="border-top:1px solid #ddd;padding-top: 30px;margin-bottom: 10px;"><?= __("Statement of Earnings and Payouts") ?></h3>

    <!--INVOICE BODY-->
    <?php foreach ($invoiceData->getAllInvoiceOrders() as $key => $order): ?>
        <?php
        $vendorData = $tableData->getVendorTableData($order);
        $totalRebate += (float)$vendorData['rebate'];
        ?>
        <div style="margin-top: 30px;"></div>
        <table class="vendor-item" cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; background-color: #ebebef; display: inline-table; font-size: 12px; font-family: Arial, Helvetica, sans-serif">
            <tr style="line-height: 20px;">
                <td style="width: 14%;"><?= __('Order ID') ?></td>
                <td style="width: 13%;"><?= __('Order Total (incl. tax)') ?></td>
                <td style="width: 13%;"><?= __('Tax Included in Order') ?></td>
                <td style="width: 12%;"><?= __('Shipping (incl. tax)') ?></td>
                <td style="width: 13%;"><?= __('Fees Total (incl. tax)') ?></td>
                <td style="width: 13%;"><?= __('Tax Included in Fees') ?></td>
                <td style="width: 11%;"><?= __('(Less) Rebates Paid') ?></td>
                <td style="width: 11%;"><?= __('Payout Amount') ?></td>
            </tr>
            <tr style="line-height: 20px;">
                <td style="width: 14%; word-wrap: break-word;"><b><?= $vendorData['increment_id'] ?></b></td>
                <td style="width: 13%;"><b><?= $vendorData['order_total_incl_tax'] ?></b></td>
                <td style="width: 13%;"><b><?= $vendorData['order_total_tax'] ?></b></td>
                <td style="width: 12%;"><b><?= $vendorData['shipping_total_order'] ?></b></td>
                <td style="width: 13%;"><b><?= $vendorData['fees_total_incl_tax'] ?></b></td>
                <td style="width: 13%;"><b><?= $vendorData['fees_total_tax'] ?></b></td>
                <td style="width: 11%;"><b><?= $vendorData['rebate'] ?></b></td>
                <td style="width: 11%;"><b><?= $vendorData['payout_amount'] ?></b></td>
            </tr>
        </table>

        <!--ORDER ITEM BODY-->
        <div style="margin-top: 10px;"></div>
        <table class="order-item" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 12px; font-family: Arial, Helvetica, sans-serif">
            <tr style="line-height: 20px; background-color: #F6F6F8;">
                <td style="width: 15%;"><?= __('SKU') ?></td>
                <td style="width: 25%;"><?= __('Item Name') ?></td>
                <td style="width: 15%; text-align: right"><?= __('Item Price (paid by customer)') ?></td>
                <td style="width: 15%; text-align: right"><?= __('Quantity') ?></td>
                <td style="width: 15%; text-align: right"><?= __('Tax Included') ?></td>
                <td style="width: 15%; text-align: right"><?= __('Subtotal') ?></td>
            </tr>
            <?php $orderItems = $tableData->getOrderItems($order->getOrderId()); ?>
            <?php foreach ($orderItems as $itemKeys => $itemOrder): ?>
                <?php if ($itemOrder->getVendorId() == $invoiceData->getVendorId()): ?>
                    <?php if ($itemOrder->getProductType() == "configurable"): ?>
                        <?php $childItems = $itemOrder->getChildrenItems(); ?>
                        <?php foreach ($childItems as $itemKey => $item): ?>
                            <?php $qty = (int)($item->getQtyOrdered() - $item->getData('qty_refunded')) ?>
                            <?php if($qty == 0) : continue; endif; ?>
                            <tr>
                                <td style="width: 15%; word-wrap: break-word; line-height: 20px;">
                                    <?= $item->getSku(); ?>
                                </td>
                                <td style="width: 25%; word-wrap: break-word; line-height: 20px;">
                                    <?= $item->getName(); ?>
                                </td>
                                <td style="width: 15%; text-align: right">
                                    <?= $tableData->currency($item->getParentItem()->getPrice()); ?>
                                </td>
                                <td style="width: 15%; text-align: right">
                                    <?= $qty * 1; ?>
                                </td>
                                <td style="width: 15%; text-align: right">
                                    <?= $tableData->currency($itemOrder->getTaxAmount()); ?>
                                </td>
                                <td style="width: 15%; text-align: right">
                                    <?= $tableData->currency($itemOrder->getRowTotal()); ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php $qty = (int)($itemOrder->getQtyOrdered() - $itemOrder->getData('qty_refunded')) ?>
                        <?php if($qty == 0) : continue; endif; ?>
                        <tr>
                            <td style="width: 15%; word-wrap: break-word; line-height: 20px;">
                                <?= $itemOrder->getSku(); ?>
                            </td>
                            <td style="width: 25%; word-wrap: break-word; line-height: 20px;">
                                <?= $itemOrder->getName(); ?>
                            </td>
                            <td style="width: 15%; text-align: right">
                                <?= $tableData->currency($itemOrder->getProduct()->getPrice()); ?>
                            </td>
                            <td style="width: 15%; text-align: right">
                                <?= $qty * 1; ?>
                            </td>
                            <td style="width: 15%; text-align: right">
                                <?= $tableData->currency($itemOrder->getTaxAmount()); ?>
                            </td>
                            <td style="width: 15%; text-align: right">
                                <?= $tableData->currency($itemOrder->getRowTotal()); ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>

    <!--FOOTER TOTAL-->
    <div style="margin-top: 30px;"></div>

    <table cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; display: inline-table; font-size: 12px; font-family: Arial, Helvetica, sans-serif;background-color: #ebebef;">
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('Total of All Orders (incl. tax)') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($invoiceData->getOrdersTotalInclTax()) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('Total Tax Included:') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($invoiceData->getOrdersTotalTax()) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('Total Shipping (incl. tax)') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($totalShippingCostCalculated) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('(Less) Total Rebates Paid:') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($totalRebate) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td colspan="2" style="width: 25%; border-bottom: solid 1px #ddd"></td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('Fees Total Payable (incl. tax):') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($invoiceData->getFeesTotalInclTax()) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('Tax Included in Fees:') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($invoiceData->getFeesTotalTax()) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td colspan="2" style="width: 25%; border-bottom: solid 1px #ddd"></td>
        </tr>
        <tr style="page-break-after: always;">
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%">
                <b><?= __('Total Earnings (incl. tax):') ?></b>
            </td>
            <td style="text-align: right; width: 15%">
                <b><?= $tableData->currency($tableData->totalEarning($invoiceData)) ?></b>
            </td>
        </tr>
        <tr>
            <td colspan="3" style="border-bottom: solid 1px #ddd;"></td>
        </tr>
    </table>

    <!--FOOTER PAID-->
    <div style="margin-top: 30px;"></div>
    <table cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif">
        <tr>
            <td style="text-align: left;">
                <b><?= __('Invoice paid via ') . $tableData->getPayoutType($invoiceData) ?></b><br>
                <p><?= $tableData->getMoName() . __(' on your behalf, charged the customer for the above orders') ?></p>
                <p><?= __('The total amount for the orders in this invoice has been released from ') . $tableData->getPayoutType($invoiceData) ?></p>
            </td>
        </tr>
    </table>
    </body>
