<?php

namespace Omnyfy\Mcm\Ui\DataProvider\PendingPayout\Grid;

use Magento\Framework\Api\FilterBuilder;
use Magento\Framework\Api\Search\SearchCriteriaBuilder;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\View\Element\UiComponent\DataProvider\Reporting;
use Magento\Framework\Api\Search\SearchResultInterface;
use Omnyfy\Mcm\Model\ResourceModel\VendorPayout;
use Omnyfy\Mcm\Helper\Data as HelperData;
use Omnyfy\Mcm\Model\ResourceModel\VendorPayoutType\CollectionFactory as VendorPayoutTypeCollection;
use Omnyfy\Mcm\Model\Config\Source\PayoutBasisType;
use Omnyfy\Vendor\Api\VendorRepositoryInterface;

/**
 * Class PendingPayoutDataProvider
 * @package Omnyfy\Mcm\Ui\DataProvider\PendingPayout\Grid
 */
class PendingPayoutDataProvider extends \Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider {

    /**
     * @var \Magento\Framework\Pricing\Helper\Data
     */
    protected $pricing;

    /**
     * @var VendorPayoutTypeCollection
     */
    protected $vendorPayoutTypeCollection;

    /**
     * @var VendorRepositoryInterface
     */
    protected $vendorRepository;

    /**
     * @var \Omnyfy\Mcm\Model\Config
     */
    protected $_config;

    /**
     * @param string                $name
     * @param string                $primaryFieldName
     * @param string                $requestFieldName
     * @param Reporting             $reporting
     * @param SearchCriteriaBuilder $searchCriteriaBuilder
     * @param RequestInterface      $request
     * @param FilterBuilder         $filterBuilder
     * @param array                 $meta
     * @param array                 $data
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     */
    public function __construct(
        $name, 
        $primaryFieldName, 
        $requestFieldName, 
        Reporting $reporting, 
        SearchCriteriaBuilder $searchCriteriaBuilder, 
        RequestInterface $request, FilterBuilder $filterBuilder, 
        \Magento\Framework\Pricing\Helper\Data $pricing, 
        VendorPayout $vendorPayoutResource, 
        HelperData $helper, 
        VendorPayoutTypeCollection $vendorPayoutTypeCollection,
        VendorRepositoryInterface $vendorRepository,
        \Omnyfy\Mcm\Model\Config $config,
        array $meta = [], 
        array $data = []
    ) {
        $this->pricing = $pricing;
        $this->vendorPayoutResource = $vendorPayoutResource;
        $this->_helper = $helper;
        $this->vendorPayoutTypeCollection = $vendorPayoutTypeCollection;
        $this->vendorRepository = $vendorRepository;
        $this->_config = $config;
        parent::__construct(
            $name, $primaryFieldName, $requestFieldName, $reporting, $searchCriteriaBuilder, $request, $filterBuilder, $meta, $data
        );
    }

    /**
     * @param SearchResultInterface $searchResult
     * @return array
     */
    protected function searchResultToOutput(SearchResultInterface $searchResult) {
        $arrItems = [];
        $arrItems['totalRecords'] = $searchResult->getTotalCount();

        $arrItems['items'] = [];
        foreach ($searchResult->getItems() as $item) {
            $arrItems['items'][] = $item->getData();
        }

        return $arrItems;
    }

    /**
     * @return mixed
     */
    public function getSearchResult()
    {
        $collection = parent::getSearchResult(); // TODO: Change the autogenerated stub
        foreach ($collection as $payout) {
            $balanceOwing = $this->vendorPayoutResource->getPendingBalanceOwingTotal($payout['vendor_id']);
            $payoutAmount = $this->vendorPayoutResource->getPayoutBalanceTotal($payout['vendor_id']);
            $vendorPayoutType = $this->vendorPayoutTypeCollection->create();
            $resource = $vendorPayoutType->getResource();
            $vendorPayoutType->addFieldToFilter('vendor_id', ['eq' => $payout->getVendorId()])
                ->join(
                    ['payout_type' => $resource->getTable('omnyfy_mcm_payout_type')],
                    'main_table.payout_type_id = payout_type.id',
                    ['payout_type']
                );
            $payout->setData('vendor_name_status', ($payout['vendor_name']) ? ($payout['vendor_status'] == 0 ? $payout['vendor_name'] . ' (Disabled)' : $payout['vendor_name']) : '');
            $payout->setData('balance_owing', $this->currency($balanceOwing));
            $payout->setData('payout_amount', $this->currency($payoutAmount));
            $payout->setData('payout_type', $vendorPayoutType->getFirstItem()->getPayoutType());

            //$payout->setData('vendor_name_status', ($payout['payout_amount']) ? $this->currency($payout['payout_amount'], true, false) : '');
        }
        return $collection;
    }

    /**
     * @param $value
     * @return mixed
     */
    public function currency($value) {
        return $this->_helper->formatToBaseCurrency($value);
    }

    /**
     * @param $vendorId
     * @return mixed
     */
    public function getVendorPayoutBasisType($vendorId){
        $vendor = $this->vendorRepository->getById($vendorId);
        return $vendor->getPayoutBasisType();
    }

}
