<?php
    $orderData = $block->getData('order_data');
    $invoiceData = $block->getData('invoice_data');
    $soldData = $block->getData('sold_data');
    $shippingData = $block->getData('shipping_data');
    $invoiceItems = $block->getData('invoice_items');
    $vendorInfo = $block->getData('vendor_info');
    $total = $block->getData('total');
    $mcmHelper = $this->helper('Omnyfy\Mcm\Helper\Data');
    $itemOptions = $block->getData('item_options');
    $orderAttributes = $block->getData('order_attributes');
    $logoSrc = $block->getData('logo_url');
    $taxline = $block->getData('taxline');
    $invoiceBy = $block->getData('invoiceBy');

    $helper = $this->helper(\Omnyfy\Mcm\Helper\PrintInvoice::class);

?>
<body class="order_invoice">
    <!--HEADING-->
    <table style="table-layout: fixed; width: 100%; line-height: 10px; font-family: Arial, Helvetica, sans-serif; font-weight: bold">
        <tr>
            <td style="width:80%; font-size: 28px; text-align: left; padding-top: 25px">
                <?= $orderData['mo_name']; ?>
            </td>
            <td>
                <img src="<?= $logoSrc; ?>" style="display: block; max-width: 132px; width: 100%; text-align: right;">
            </td>
        </tr>
    </table>
    <div style="margin-top: 30px;"></div>

    <div style="font-size: 32px; margin-bottom: 30px; font-family: Arial, Helvetica, sans-serif; font-weight: bold; padding-left: 5px;">
        <b><?= __('Order Invoice') ?></b>
    </div>
    <table class="header" cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; font-size: 13px; font-family: Arial, Helvetica, sans-serif">
        <tr>
            <td style="text-align: left;vertical-align: text-top;">
                <b><?= __('Invoice To') ?></b>
                <br/>
                <br/>
                <?= $soldData['customer_name'] ?>
                <br/>
                <br/>
                <br/>
                <br/>
                <b><?= __('Order Invoice') ?></b>
                <br/>
                <br/>
                <?= __('Invoice #: ') . $block->getData('invoice_increment_id'); ?>
                <br/>
                <br/>
                <?= __('Order #: ') . $orderData['increment_id'] ?>
                <br/>
                <br/>
                <?= __('Order Date: ') . $orderData['date'] ?>
            </td>
            <?php if($invoiceBy == 1): ?>
            <td style="text-align: right;vertical-align: text-top;">
                <b><?= __('Invoice from') ?></b>
                <br/>
                <br/>
                <?= $invoiceData['invoice_name'] ?>
                <br/>
                <br/>
                <?= __('Tax Number: ') . $invoiceData['tax_number'] ?>
                <br/>
                <br/>
                <?= $invoiceData['address_line1'] . ', ' . $invoiceData['address_line2'] ?>
                <br/>
                <br/>
                <?= $invoiceData['city'] . ', ' . $invoiceData['post_code'] . ', ' . $invoiceData['region_name'] ?>
                <br/>
                <br/>
                <?= $invoiceData['country_name'] ?>
            </td>
            <?php endif; ?>
        </tr>
    </table>

    <!--SOLD AND SHIP-->
    <div style="margin-top: 30px;"></div>
    <table class="sold-ship" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif;">
        <tr style="background-color: #F6F6F8;">
            <td style="text-align: left; padding: 10px;">
                <b><?= __('Sold To') ?></b>
            </td>
            <td style="text-align: left; padding: 10px;">
                <b><?= __('Ship To') ?></b>
            </td>
        </tr>
        <tr>
            <td style="text-align: left; padding-top: 15px; padding-left: 10px;"><?= $soldData['customer_name'] ?></td>
            <td style="text-align: left; padding-top: 15px; padding-left: 10px;"><?= $shippingData['customer_name'] ?></td>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= $soldData['street'] ?></td>
            <td style="text-align: left; padding-left: 10px;"><?= $shippingData['street'] ?></td>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= $soldData['city'] ?></td>
            <td style="text-align: left; padding-left: 10px;"><?= $shippingData['city'] ?></td>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= $soldData['country'] ?></td>
            <td style="text-align: left; padding-left: 10px;"><?= $shippingData['country'] ?></td>
        </tr>
        <tr>
            <td style="text-align: left; padding-left: 10px;"><?= __('T: ') . $soldData['telephone'] ?></td>
            <td style="text-align: left; padding-left: 10px;"><?= __('T: ') . $shippingData['telephone'] ?></td>
        </tr>
    </table>

    <!--PAYMENT AND SHIPPING-->
    <div style="margin-top: 30px;"></div>
    <table class="payment-ship" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif;">
        <tr style="background-color: #F6F6F8;">
            <td style="text-align: left; padding: 10px;">
                <b><?= __('Payment Method') ?></b>
            </td>
        </tr>
        <tr>
            <?php if(!isset($orderData['payment']['of_payment'])): ?>
                <td style="text-align: left; padding-left: 10px; padding-top: 15px;"><?= $orderData['payment'][0] ?></td>
            <?php else: ?>
                <td style="text-align: left; padding-left: 10px; padding-top: 15px;"><?= $orderData['payment']['of_payment'][0] ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <?php if(!isset($orderData['payment']['of_payment'])): ?>
                <td style="text-align: left; padding-left: 10px;"><?= $orderData['payment'][1] ?></td>
            <?php else: ?>
                <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <?php if(!isset($orderData['payment']['of_payment'])): ?>
                <td style="text-align: left; padding-left: 10px;"><?= $orderData['payment'][2] ?></td>
            <?php else: ?>
                <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
            <?php endif; ?>
        </tr>
    </table>
    <?php
        if(!empty($orderAttributes)):
    ?>
        <table class="order-attributes" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-size: 13px; font-family: Arial, Helvetica, sans-serif; margin-top: 30px">
            <tr style="line-height: 20px; background-color: #F6F6F8;">
                <td colspan="6" style="text-align: left;">
                    <b>Additional Data</b>
                </td>
            </tr>

            <?php
                foreach ($orderAttributes as $orderAttribute):
            ?>
                <tr style="width: 100%; line-height: 20px;">
                    <td colspan="6">
                        <b><?=$orderAttribute['label']?> : </b> <?= $orderAttribute['value']?>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    <?php endif;?>

    <!--ORDER ITEMS-->
    <div style="margin-top: 30px;"></div>


    <?php foreach ($block->getData('vendors') as $vendor): ?>
        <?php
            $vendorAddress = $helper->getVendorAddress($vendor);
        ?>
        <style type="text/css">
            .order-item td{
                vertical-align: top;
                line-height: 18px;
            }
        </style>
        <table class="order-item" cellpadding="5px" style="table-layout: fixed; width: 100%; border-collapse: collapse; line-height: 10px; display: inline-table; font-family: Arial, Helvetica, sans-serif; font-size: 13px;">
            <tr style="background-color: #F6F6F8;">
                <td colspan="7" style="text-align: left;">
                    <b>
                        <?= $vendorAddress['business_name'] ?: null ?>
                        -        
                        <?= $vendorAddress['tax_number'] ?: __("Tax Number") ?>:
                        <?= $vendorAddress['abn'] ?: null ?>
                    </b>
                </td>
            </tr>
            <?php if($invoiceBy == 2): ?>
            <tr>
                <td colspan="7" style="text-align: left;">
                    <?= $vendorAddress['business_address'] ?: null ?>
                    <br/>
                    <?= $vendorAddress['city'] ?: null ?>,
                    <?= $vendorAddress['state'] ?: null ?>,
                    <?= $vendorAddress['country'] ?: null ?><br/>
                    <?= $vendorAddress['postcode'] ?: null ?>
                </td>
            </tr>
            <?php endif; ?>

            <tr>
                <td></td>
            </tr>
            <tr style="background-color: #F6F6F8;">
                <td style="width: 24%; text-align: left;"><?= __('Products') ?></td>
                <td style="width: 17%; text-align: left;"><?= __('SKU') ?></td>
                <td style="width: 17%; text-align: right"><?= __('Price') ?></td>
                <td style="width: 6%; text-align: right"><?= __('Qty') ?></td>

                <?php if($taxline): ?>
                <td style="width: 12%; text-align: right"><?= __('Tax Name') ?></td>
                <?php endif; ?>

                <td style="width: 12%; text-align: right"><?= __('Tax') ?></td>
                <td style="width: 12%; text-align: right"><?= __('Subtotal') ?></td>
            </tr>
            <?php foreach ($invoiceItems as $invoiceItem): ?>
                <?php if ($vendor == $invoiceItem->getVendorId()): ?>
                    <?php
                    if ($invoiceItem->getOrderItem()->getParentItem()){
                        continue;
                    }
                    ?>
                    <tr>
                        <td style="width: 24%; word-wrap: break-word;">
                            <strong></strong><?= $invoiceItem->getName() ?></strong>

                            <?php if (!empty($itemOptions) && isset($itemOptions[$invoiceItem->getSku()])): ?>
                                <?php foreach ($itemOptions[$invoiceItem->getSku()] as $_option): ?>
                                    <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                                    <p>
                                        <strong><?= $block->escapeHtml($_option['label']) ?></strong>:
                                        <span><?= $block->escapeHtml($optionValue) ?></span>
                                    </p>
                                <?php endforeach; ?>
                            <?php endif; ?>


                        </td>
                        <td style="width: 17%; word-wrap: break-word;"><?= $invoiceItem->getSku() ?></td>
                        <td style="width: 17%; text-align: right"><?= $mcmHelper->formatToBaseCurrency($invoiceItem->getPrice()) ?></td>
                        <td style="width: 6%; text-align: right"><?= $invoiceItem->getQty() * 1 ?></td>
                        <?php if($taxline): ?>
                        <td style="text-align: right;">
                            <?= implode("<br/>", array_map(function($tax){
                                    return __("%1: %2%", $tax->getTitle(), (int)$tax->getTaxPercent());
                               }, $taxline->getOrderItemTax($invoiceItem->getOrderItem()))); ?>
                        </td>
                        <?php endif; ?>
                        <td style="width: 12%; text-align: right"> <?= $mcmHelper->formatToBaseCurrency($invoiceItem->getTaxAmount()) ?> </td>
                        <td style="width: 12%; text-align: right"> <?= $mcmHelper->formatToBaseCurrency($invoiceItem->getRowTotal()) ?> </td>
                    </tr>
                <?php endif; ?>
                <?php if (false && !empty($itemOptions) && isset($itemOptions[$invoiceItem->getSku()])): ?>
                    <?php
                    $_options = $itemOptions[$invoiceItem->getSku()];
                    ?>
                    <?php foreach ($_options as $_option): ?>
                        <tr>
                            <td><b><?= $block->escapeHtml($_option['label']) ?></b></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                        </tr>
                        <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                        <tr>
                            <td><?= $block->escapeHtml($optionValue) ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                            <td style="text-align: left; padding-left: 10px;"><?= __('') ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>

    <!--FOOTER TOTAL-->
    <div style="margin-top: 30px;"></div>
    <table cellpadding="5px" style="table-layout: fixed; width: 100%; line-height: 10px; display: inline-table; border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; font-size: 13px;">
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8; padding-top: 15px;">
                <b><?= __('Subtotal:') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8; padding-top: 15px;">
                <b><?= $mcmHelper->formatToBaseCurrency($total['subtotal']) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                <b><?= __('Shipping & Handling:') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                <b><?= $mcmHelper->formatToBaseCurrency($total['shipping']) ?></b>
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                <b><?= __('Tax:') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                <b><?= $mcmHelper->formatToBaseCurrency($total['tax']) ?></b>
            </td>
        </tr>

        <?php if(count($block->getData('vendors')) > 1): ?>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8;">
                <b><?= __('Transaction Fee (incl.Tax):') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8;">
                <b><?= $mcmHelper->formatToBaseCurrency($total['transaction_fee_incl_tax']) ?></b>
            </td>
        </tr>
        <?php endif; ?>

        <tr>
            <td style="width: 50%"></td>
            <td colspan="2" style="padding-left: 10px; padding-right: 10px; background-color: #F6F6F8;">
                <hr style="border-bottom: solid 2px #ebebef;">
            </td>
        </tr>
        <tr>
            <td style="width: 50%"></td>
            <td style="text-align: right; width: 35%; background-color: #F6F6F8; padding-bottom: 15px;">
                <b><?= __('Grand Total :') ?></b>
            </td>
            <td style="text-align: right; width: 15%; background-color: #F6F6F8; padding-bottom: 15px;">
                <b><?= $mcmHelper->formatToBaseCurrency($total['grand_total']) ?></b>
            </td>
        </tr>
    </table>
</body>
