<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \OmnyfyCustomzation\B2C\Block\Trade\Register $block */
$email = $block->getCustomerEmail();
$customer = $block->getCustomer();
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionCreate()) ?>"
      method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */
    $block->getBlockHtml('formkey'); ?>
    <p class="title additional"><?= __('Sign up to view trade prices and get full access to our product catalogue and dedicated support services.') ?></p>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Your Information')) ?></span></legend>
        <br>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">

        <?php if (!$block->isLoggedIn()): ?>
            <div class="field field-name-firstname required">
                <label class="label" for="firstname"><span><?= __('First Name') ?></span></label>
                <div class="control">
                    <input type="text" id="firstname"
                           name="firstname"
                           value="<?= $customer ? $customer->getFirstname() : '' ?>"
                           title="<?= __('First Name') ?>"
                           class="input-text" data-validate="{required:true}">
                </div>
            </div>

            <div class="field field-name-lastname required">
                <label class="label" for="lastname"><span><?= __('First Name') ?></span></label>
                <div class="control">
                    <input type="text" id="lastname"
                           name="lastname"
                           value="<?= $customer ? $customer->getLastname() : '' ?>"
                           title="<?= __('Last Name') ?>"
                           class="input-text" data-validate="{required:true}">
                </div>
            </div>
        <?php endif; ?>
        <div class="field business required">
            <label for="custom_field" class="label"><span><?= __('Business Name') ?></span></label>
            <div class="control">
                <input type="text" name="business_name" id="business_field"
                       value=""
                       title="<?= __('Business Name') ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

        <div class="field businessurl required">
            <label for="custom_field" class="label"><span><?= __('Business URL or social media link') ?></span></label>
            <div class="control">
                <input type="text" name="business_url" id="businessurl_field"
                       value=""
                       title="<?= __('Business URL or social media link') ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

        <div class="field designation">
            <label for="custom_field" class="label"><span><?= __('Your Designation') ?></span></label>
            <div class="control">
                <input type="text" name="designation" id="designation_field"
                       value=""
                       title="<?= __('Your Designation') ?>"
                       class="input-text">
            </div>
        </div>

        <div class="field location required">
            <label for="business_location" class="label"><span><?= __('Business Location') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect('', 'business_location', 'business_location', 'Business Location') ?>
            </div>
        </div>

        <?php if (!$block->isLoggedIn()): ?>
            <div class="field phone">
                <label for="region" class="label"><span><?= __('Phone Number') ?></span></label>
                <div class="control">
                    <?php
                    /** @var \OmnyfyCustomzation\Customer\Block\Widget\CountryCode $countryCodeWidget */
                    $countryCodeWidget = $block->getLayout()
                        ->createBlock(\OmnyfyCustomzation\Customer\Block\Widget\CountryCode::class);
                    $countryCodeOptions = $countryCodeWidget->getOptions();
                    $countryCode = $customer ? $customer->getCountryCode() : '';
                    ?>
                    <select id="countrycode" name="country_code" title="<?= $block->escapeHtml(__('Country code')) ?>">
                        <option value=""><?= $block->escapeHtml(__('Country code')) ?></option>
                        <?php foreach ($countryCodeOptions as $option): ?>
                            <?php if ($option->getValue() == '') continue; ?>
                            <option
                                value="<?= $option->getValue() ?>"<?= $countryCode == $option->getValue() ? ' selected="selected"' : '' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
                        <?php endforeach; ?>
                    </select>

                    <input type="text" name="phone_number" id="phone"
                           value="<?= $customer ? $customer->getPhoneNumber() : '' ?>"
                           title="<?= __('Phone Number') ?>"
                           class="input-text" autocomplete="off">
                </div>
            </div>
        <?php endif ?>
        <?= $block->getLayout()
            ->createBlock(\OmnyfyCustomzation\Customer\Block\Widget\BusinessType::class)
            ->setBusinessType($block->getFormData()->getBusinessType())
            ->toHtml()
        ?>

        <div class="field choice newsletter">
            <input type="checkbox" data-validate="{required:true}" name="custom-terms"
                   title="<?php /* @escapeNotVerified */
                   echo __('Terms and contitions') ?>" id="custom-terms" class="checkbox">
            <label for="custom-terms" class="label">
                <span class="red-star">*</span>
                <?php /* @escapeNotVerified */echo __('I have read and accepted Vermillion\'s') ?>
                <a class="padding-title-mb" href="/terms-and-conditions"> <?php /* @escapeNotVerified */echo __('Terms and Conditions') ?></a>
                <span><?php /* @escapeNotVerified */
                    echo __('and') ?></span>
                <a class="padding-title" href="/privacy-policy"> <?php /* @escapeNotVerified */echo __('Privacy Policy.') ?></a>
            </label>
        </div>

        <?php if ($block->isNewsletterEnabled()) : ?>
            <div class="field choice newsletter">

                <input type="checkbox" name="is_subscribed"
                       title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"
                       checked="checked" class="checkbox">
                <label for="is_subscribed"
                       class="label"><span><?= $block->escapeHtml(__('By checking this box you agree to receive emails about new designers, products and exclusives from Vermillion Lifestyle.')) ?></span></label>
            </div>
            <?= $block->getChildHtml('customer.form.register.newsletter') ?>
        <?php endif ?>
    </fieldset>
    <?php if (!$block->isLoggedIn()): ?>
        <fieldset class="fieldset create account"
                  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <legend class="legend signin"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend>
            <br>
            <div class="field required">
                <label for="email_address"
                       class="label"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" autocomplete="email" id="email_address"
                           value="<?= $email ? $email : '' ?>" title="<?= __('Email') ?>"
                           data-mage-init='{"mage/trim-input":{}}' class="input-text"
                           data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <div class="field password required">
                <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password"
                           title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           class="input-text"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirmation required">
                <label for="password-confirmation"
                       class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation"
                           title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation"
                           class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
    <?php endif ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"
                    title="<?= $block->escapeHtmlAttr(__('Sign Up To Trade')) ?>">
                <span><?= $block->escapeHtml(__('Sign Up To Trade')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
<?php if ($block->getShowAddressFields()) : ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }

    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }

</script>
