<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@omnyfy.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

use OmnyfyCustomzation\CmsBlog\Block\Article\View\Opengraph;

?>
<?php
/**
 * Cms article og:tags
 *
 * @var $block Opengraph
 */
?>

    <meta property="og:type" content="<?php echo $block->escapeHtml($block->getType()); ?>"/>
    <meta property="og:title" content="<?php echo $block->escapeHtml($block->getTitle()); ?>"/>
    <meta property="og:description" content="<?php echo $block->escapeHtml($block->getDescription()); ?>"/>
    <meta property="og:url" content="<?php echo $block->escapeHtml($block->getPageUrl()); ?>"/>
<?php if ($image = $block->getImage()) { ?>
    <meta property="og:image" content="<?php echo $block->escapeHtml($image); ?>"/>
<?php } ?>
