<?php
/**
 * @var $block RelatedVendors
 */

use OmnyfyCustomzation\CmsBlog\Block\Article\View\RelatedVendors;

?>
<?php
$vendors = $block->getVendors();
$title = __('Related Vendors');
?>
<?php if ($vendors->getSize() > 0 && $block->displayVendors()) : ?>
    <div class="block-title title">
        <strong id="block-related-heading" role="heading" aria-level="2"><?php echo $title; ?></strong>
    </div>
    <div class="vendors-wrapper vendors-grid">
        <ol class="vendors grid items vendor-items">
            <?php foreach ($vendors as $vendor) : ?>
                <?php
                $isSearchByLocation = $block->isSearchByLocation($vendor->getVendorTypeId());
                if ($isSearchByLocation) {
                    $vendorLink = $block->getLocationUrl($vendor->getId());
                    $logoLink = $block->getImage($vendor->getData('vendor_id'));
                    $attrData = $block->getLocationVendorData($vendor->getData('vendor_id'));
                } else {
                    $vendorLink = $block->getUrl("shop/brands/view/id/" . $vendor->getVendorId());
                    $logoLink = $block->getImage($vendor->getVendorId());
                    $attrData = $block->getVendorData($vendor);
                }
                ?>
                <li class="vendor-item vendor item">
                    <a href="<?php echo $vendorLink ?>" class="vendor-item-link">
                        <div class="vendor-item-info">
                            <div class="vendor-item-photo photo">
                                <img src="<?php echo $logoLink ?>" class="photo-image">
                            </div>

                            <div class="vendor vendor-item-details details">
                                <h5 class="vendor-name"><?php echo $vendor->getData('name'); ?></h5>

                                <?php if ($attrData): ?>
                                    <?php foreach ($attrData as $attr): ?>
                                        <?php if ($attr["type"] == "multiselect"): ?>
                                            <?php if (!empty($attr["data"])): ?>
                                                <?php if (is_array($attr["data"])): ?>
                                                    <ul class="vendor-tags-list">
                                                        <?php foreach ($attr["data"] as $data): ?>
                                                            <li class="vendor-tag"><?php echo $data ?></li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                <?php else: ?>
                                                    <ul class="vendor-attributes-list">
                                                        <li class="vendor-attribute">
                                                            <span
                                                                class="vendor-attribute-label"><?= $attr["label"] ?></span>
                                                            <span
                                                                class="vendor-attribute-value"><?= $attr["data"] ?></span>
                                                        </li>
                                                    </ul>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>

                                <div class="info-left">
                                    <span class="info-text"><?php echo $vendor->getData("location_name") ?></span>
                                    <?php if ($vendor->getData("location_count") > 0): ?>
                                        <span class="more">and <?php echo $vendor->getData("location_count") ?> more locations</span>
                                    <?php endif; ?>
                                </div>

                            </div>
                        </div>
                    </a>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>
